/**
 * Agency / Freelance industry template — full end-to-end.
 *
 * Pipeline: Inquiry → Quote Sent → Deposit Paid → In Progress → Review →
 *           Invoiced → Complete | Cancelled.
 *
 * Entity renames:
 *   Lead    → Inquiry
 *   Contact → Client
 *   Deal    → Project
 *   Company → Agency (for sub-contractors / partner agencies)
 */
import type { IndustryTemplate } from "../types";

export const agencyFreelanceTemplate: IndustryTemplate = {
	id: "agency-freelance",
	label: "Agency / Freelance",
	description:
		"Project-based creative work — inquiry, quote, deposit, deliver, invoice. Retainer + milestone tracking.",
	icon: "🎨",
	region: "global",

	defaults: {
		currency: "USD",
		timezone: "UTC",
		leadStaleAfterDays: 7,
		locale: "en",
	},

	entityLabels: {
		lead: { singular: "Inquiry", plural: "Inquiries", slug: "inquiries" },
		contact: { singular: "Client", plural: "Clients", slug: "clients" },
		deal: { singular: "Project", plural: "Projects", slug: "projects" },
		company: { singular: "Agency", plural: "Agencies", slug: "agencies" },
	},

	codePrefixes: { person: "INQ", deal: "PRJ", company: "AG", followup: "FU" },

	pipeline: {
		name: "Project Pipeline",
		stages: [
			{ name: "Inquiry", code: "INQ", color: "#6366f1", staleAfterDays: 5 },
			{ name: "Quote Sent", code: "QUOTE", color: "#8b5cf6", staleAfterDays: 5 },
			{ name: "Deposit Paid", code: "DEP", color: "#a855f7", staleAfterDays: 7 },
			{ name: "In Progress", code: "WIP", color: "#f59e0b", staleAfterDays: 21 },
			{ name: "Review / Feedback", code: "REV", color: "#3b82f6", staleAfterDays: 7 },
			{ name: "Invoiced", code: "INV", color: "#06b6d4", staleAfterDays: 14 },
			{
				name: "Complete",
				code: "DONE",
				color: "#22c55e",
				isFinal: true,
				finalType: "positive",
			},
			{
				name: "Cancelled",
				code: "CXL",
				color: "#ef4444",
				isFinal: true,
				finalType: "negative",
			},
		],
	},

	fieldDefinitions: {
		lead: [
			{
				entityType: "lead",
				name: "project_type",
				label: "Project Type",
				type: "select",
				kind: "select",
				storage: "fieldValues",
				groupName: "Brief",
				options: [
					"Website",
					"Branding",
					"App Design",
					"Marketing",
					"Video",
					"Copywriting",
					"Consulting",
					"Other",
				],
			},
			{
				entityType: "lead",
				name: "budget_range",
				label: "Budget Range",
				type: "select",
				kind: "select",
				storage: "fieldValues",
				groupName: "Brief",
				options: ["< $1K", "$1K–$5K", "$5K–$15K", "$15K–$50K", "$50K+"],
			},
			{
				entityType: "lead",
				name: "deadline",
				label: "Desired Deadline",
				type: "date",
				kind: "date",
				storage: "fieldValues",
				groupName: "Brief",
			},
			{
				entityType: "lead",
				name: "referral_source",
				label: "How they found you",
				type: "select",
				kind: "select",
				storage: "fieldValues",
				groupName: "Attribution",
				options: [
					"Portfolio",
					"Referral",
					"Social media",
					"Google",
					"Dribbble/Behance",
					"Cold outreach",
					"Repeat client",
					"Other",
				],
			},
		],
		contact: [
			{
				entityType: "contact",
				name: "company_name",
				label: "Company Name",
				type: "text",
				kind: "text",
				storage: "fieldValues",
				groupName: "Client",
			},
			{
				entityType: "contact",
				name: "billing_email",
				label: "Billing Email",
				type: "email",
				kind: "email",
				storage: "fieldValues",
				groupName: "Billing",
			},
			{
				entityType: "contact",
				name: "payment_terms",
				label: "Payment Terms",
				type: "select",
				kind: "select",
				storage: "fieldValues",
				groupName: "Billing",
				options: ["50% upfront", "Net 15", "Net 30", "Milestone-based", "Retainer"],
			},
		],
		deal: [
			{
				entityType: "deal",
				name: "scope_summary",
				label: "Scope Summary",
				type: "text",
				kind: "text",
				storage: "fieldValues",
				groupName: "Scope",
			},
			{
				entityType: "deal",
				name: "quoted_amount",
				label: "Quoted Amount",
				type: "currency",
				kind: "currency",
				storage: "fieldValues",
				groupName: "Financial",
			},
			{
				entityType: "deal",
				name: "deposit_amount",
				label: "Deposit Amount",
				type: "currency",
				kind: "currency",
				storage: "fieldValues",
				groupName: "Financial",
				showInStages: ["DEP", "WIP", "REV", "INV", "DONE"],
			},
			{
				entityType: "deal",
				name: "deposit_paid_date",
				label: "Deposit Paid Date",
				type: "date",
				kind: "date",
				storage: "fieldValues",
				groupName: "Financial",
				showInStages: ["DEP", "WIP", "REV", "INV", "DONE"],
			},
			{
				entityType: "deal",
				name: "estimated_hours",
				label: "Estimated Hours",
				type: "number",
				kind: "number",
				storage: "fieldValues",
				groupName: "Scope",
			},
			{
				entityType: "deal",
				name: "hourly_rate",
				label: "Hourly Rate",
				type: "currency",
				kind: "currency",
				storage: "fieldValues",
				groupName: "Financial",
			},
			{
				entityType: "deal",
				name: "delivery_date",
				label: "Delivery Date",
				type: "date",
				kind: "date",
				storage: "fieldValues",
				groupName: "Scope",
				showInStages: ["WIP", "REV", "INV", "DONE"],
			},
			{
				entityType: "deal",
				name: "invoice_number",
				label: "Invoice #",
				type: "text",
				kind: "text",
				storage: "fieldValues",
				groupName: "Billing",
				showInStages: ["INV", "DONE"],
			},
			{
				entityType: "deal",
				name: "invoice_amount",
				label: "Invoice Amount",
				type: "currency",
				kind: "currency",
				storage: "fieldValues",
				groupName: "Billing",
				showInStages: ["INV", "DONE"],
			},
			{
				entityType: "deal",
				name: "invoice_paid_date",
				label: "Invoice Paid Date",
				type: "date",
				kind: "date",
				storage: "fieldValues",
				groupName: "Billing",
				showInStages: ["DONE"],
			},
			{
				entityType: "deal",
				name: "revision_count",
				label: "Revision Count",
				type: "number",
				kind: "number",
				storage: "fieldValues",
				groupName: "Scope",
				showInStages: ["REV", "INV", "DONE"],
			},
		],
	},

	modules: [
		{
			slot: "lead",
			order: 0,
			defaultView: "list",
			cardFields: ["displayName", "project_type", "budget_range", "deadline"],
			listColumns: [
				"displayName",
				"personCode",
				"project_type",
				"budget_range",
				"deadline",
				"referral_source",
				"assignedTo",
				"status",
			],
			boardGroupBy: "status",
		},
		{
			slot: "contact",
			order: 1,
			defaultView: "list",
			cardFields: ["displayName", "company_name", "payment_terms"],
			listColumns: [
				"displayName",
				"personCode",
				"email",
				"company_name",
				"payment_terms",
				"assignedTo",
			],
			boardGroupBy: "assignedTo",
		},
		{
			slot: "deal",
			order: 2,
			defaultView: "board",
			cardFields: ["title", "quoted_amount", "delivery_date", "assignedTo"],
			listColumns: [
				"dealCode",
				"title",
				"quoted_amount",
				"estimated_hours",
				"delivery_date",
				"currentStageId",
				"assignedTo",
			],
			boardGroupBy: "currentStageId",
		},
		{
			slot: "company",
			order: 3,
			defaultView: "list",
			hidden: true,
			cardFields: ["name", "industry"],
			listColumns: ["name", "companyCode", "industry", "assignedTo"],
			boardGroupBy: "assignedTo",
		},
	],

	noteCategories: [
		{ name: "Urgent", bgColor: "#fecaca", isDefault: false, position: 0 },
		{ name: "Today", bgColor: "#fde68a", isDefault: true, position: 1 },
		{ name: "Brief", bgColor: "#bae6fd", isDefault: false, position: 2 },
		{ name: "Review", bgColor: "#ddd6fe", isDefault: false, position: 3 },
		{ name: "Done", bgColor: "#a7f3d0", isDefault: false, position: 4 },
	],

	tags: [
		{ name: "Rush job", color: "#ef4444" },
		{ name: "Retainer", color: "#3b82f6" },
		{ name: "Repeat client", color: "#22c55e" },
		{ name: "Scope creep", color: "#f59e0b" },
		{ name: "Overdue payment", color: "#dc2626" },
		{ name: "Portfolio piece", color: "#a855f7" },
		{ name: "Referral source", color: "#06b6d4" },
		{ name: "Pro bono", color: "#94a3b8" },
	],

	reminderDefaults: {
		followUpWindowHours: 48,
		staleAlertDays: 7,
		morningBriefingEnabled: false,
		morningBriefingTime: "09:00",
	},

	followupDefaults: {
		defaultDueOffsetDays: 3,
		defaultPriority: "normal",
		notifyAssignee: true,
		requireDealCode: true,
		reminderBeforeHours: 2,
	},

	fileUpload: {
		allowedMimeCategories: ["image", "pdf", "document", "video", "archive"],
		maxSizeMb: 50,
	},

	aiPersona:
		"You are a freelance/agency project management assistant. Help the user track inquiries, send quotes, manage project scope, track revisions, and follow up on invoices. Refer to leads as 'inquiries', contacts as 'clients', deals as 'projects', companies as 'agencies'. Understand scope creep, revision limits, deposit-before-work policies, and milestone billing. When a project is stuck in Review, suggest a follow-up. When an invoice is overdue (>14 days in Invoiced stage), flag it urgently. Always confirm before marking a project as Cancelled.",

	dashboardMetrics: [
		"deals.open",
		"deals.pipelineValue",
		"deals.invoiced.unpaid",
		"reminders.dueToday",
		"deals.pipeline",
		"reminders.list",
		"messages.recent",
		"today.focus",
	],

	customRoles: [
		{
			name: "Account Manager",
			description: "Owns client relationships — quotes, scope, invoicing.",
			color: "#3b82f6",
			permissions: [
				"leads.view",
				"leads.create",
				"leads.update",
				"leads.qualify",
				"leads.convert",
				"contacts.view",
				"contacts.create",
				"contacts.update",
				"companies.view",
				"deals.view",
				"deals.create",
				"deals.update",
				"deals.changeStage",
				"deals.viewValues",
				"deals.close",
				"notes.view",
				"notes.create",
				"notes.updateOwn",
				"notes.deleteOwn",
				"messages.view",
				"messages.send",
				"messages.editOwn",
				"messages.deleteOwn",
				"messages.subscribe",
				"reminders.view",
				"reminders.create",
				"reminders.manage",
				"tags.view",
				"tags.attach",
				"savedViews.view",
				"savedViews.createPersonal",
				"pipelines.view",
				"fieldDefinitions.view",
				"ai.use",
				"ai.viewHistory",
				"activityLogs.viewOwn",
				"notifications.viewOwn",
				"notifications.markRead",
				"files.view",
				"files.upload",
				"files.delete",
			],
		},
		{
			name: "Creative",
			description: "Executes work — sees projects in progress, adds notes + files.",
			color: "#a855f7",
			permissions: [
				"deals.view",
				"deals.update",
				"deals.changeStage",
				"deals.viewValues",
				"notes.view",
				"notes.create",
				"notes.updateOwn",
				"notes.deleteOwn",
				"messages.view",
				"messages.send",
				"messages.editOwn",
				"messages.deleteOwn",
				"messages.subscribe",
				"reminders.view",
				"reminders.create",
				"reminders.manage",
				"tags.view",
				"tags.attach",
				"savedViews.view",
				"savedViews.createPersonal",
				"pipelines.view",
				"fieldDefinitions.view",
				"ai.use",
				"activityLogs.viewOwn",
				"notifications.viewOwn",
				"notifications.markRead",
				"files.view",
				"files.upload",
				"files.delete",
			],
		},
	],

	savedViews: [
		{
			entityType: "deal",
			name: "Active projects",
			scope: "org",
			isPinned: true,
			filters: JSON.stringify({ excludeFinal: true }),
			sortBy: "delivery_date",
			sortOrder: "asc",
		},
		{
			entityType: "deal",
			name: "Awaiting deposit",
			scope: "org",
			isPinned: true,
			filters: JSON.stringify({ stage: "QUOTE" }),
			sortBy: "createdAt",
			sortOrder: "asc",
		},
		{
			entityType: "deal",
			name: "In review (feedback needed)",
			scope: "org",
			isPinned: true,
			filters: JSON.stringify({ stage: "REV" }),
			sortBy: "updatedAt",
			sortOrder: "asc",
		},
		{
			entityType: "deal",
			name: "Overdue invoices",
			scope: "org",
			isPinned: true,
			filters: JSON.stringify({ stage: "INV", staleAfterDays: 14 }),
			sortBy: "stageEnteredAt",
			sortOrder: "asc",
		},
		{
			entityType: "lead",
			name: "New inquiries (mine)",
			scope: "user",
			isPinned: true,
			filters: JSON.stringify({ assignedToMe: true, status: "new" }),
			sortBy: "createdAt",
			sortOrder: "desc",
		},
	],

	// ─── Mock data (Phase 3A — deletable sample records) ──────────────────
	mockData: {
		companies: [
			{
				key: "northwind-creative",
				name: "Northwind Creative",
				industry: "Agency",
				website: "https://northwind.example.com",
			},
		],
		leads: [
			{
				displayName: "Tom Bauer",
				email: "tom.b@example.com",
				phone: "+1 415 555 0301",
				status: "new",
				fieldValues: {
					project_type: "Branding",
					budget_range: "$15K–$50K",
					deadline: Date.now() + 30 * 86_400_000,
					referral_source: "Portfolio",
				},
			},
			{
				displayName: "Eva Larsson",
				email: "eva.l@example.com",
				status: "contacted",
				fieldValues: {
					project_type: "Website",
					budget_range: "$5K–$15K",
					deadline: Date.now() + 21 * 86_400_000,
					referral_source: "Referral",
				},
			},
			{
				displayName: "Carlos Mendes",
				email: "carlos@example.com",
				status: "new",
				fieldValues: {
					project_type: "Video",
					budget_range: "$1K–$5K",
					referral_source: "Social media",
				},
			},
		],
		contacts: [
			{
				displayName: "Aria Thompson",
				email: "aria@example.com",
				phone: "+1 213 555 0310",
				companyKey: "northwind-creative",
				fieldValues: {
					company_name: "Northwind Creative",
					payment_terms: "50% upfront",
				},
			},
			{
				displayName: "Riku Yamada",
				email: "riku@example.com",
				fieldValues: {
					payment_terms: "Milestone-based",
				},
			},
		],
		deals: [
			{
				title: "Northwind — Website redesign",
				stageCode: "WIP",
				value: 12000,
				contactDisplayName: "Aria Thompson",
				companyKey: "northwind-creative",
				fieldValues: {
					scope_summary: "Marketing site redesign — homepage + 6 inner pages + CMS migration.",
					quoted_amount: 12000,
					deposit_amount: 6000,
					estimated_hours: 80,
					hourly_rate: 150,
					delivery_date: Date.now() + 21 * 86_400_000,
				},
				tags: ["Repeat client"],
			},
			{
				title: "Riku — Brand identity",
				stageCode: "REV",
				value: 8500,
				contactDisplayName: "Riku Yamada",
				fieldValues: {
					scope_summary: "Logo + brand guide + business card mockups.",
					quoted_amount: 8500,
					estimated_hours: 60,
					delivery_date: Date.now() + 7 * 86_400_000,
					revision_count: 2,
				},
			},
		],
		notes: [
			{
				content: "Northwind kickoff call — confirmed scope + signed deposit invoice.",
				categoryName: "Brief",
				anchorTo: { kind: "deal", title: "Northwind — Website redesign" },
			},
			{
				content: "Riku requested third revision on logo color palette. Track scope.",
				categoryName: "Review",
				anchorTo: { kind: "deal", title: "Riku — Brand identity" },
			},
			{
				content: "Tom asked for portfolio samples in agency style — send Wednesday.",
				categoryName: "Today",
				anchorTo: { kind: "lead", displayName: "Tom Bauer" },
			},
		],
		reminders: [
			{
				title: "Northwind — homepage v1 to client",
				dueOffsetDays: 3,
				priority: "high",
				source: "followup",
				anchorTo: { kind: "deal", title: "Northwind — Website redesign" },
			},
			{
				title: "Riku — present revised logo set",
				dueOffsetDays: 1,
				priority: "high",
				source: "manual",
				anchorTo: { kind: "deal", title: "Riku — Brand identity" },
			},
		],
	},
};
