/**
 * convex/ai/tools/analytics/getBriefing.ts
 *
 * Stage 7 (`/SPRINT-PLAN.md`) — closes AI-AUDIT-COMPLETE.md §16 P3 row
 * 16. Atomic read tool returning the latest unexpired daily-user OR
 * weekly-org briefing. Wraps the existing `briefingsPublic` ForAI twins
 * (Stage 7 added them).
 */

import { z } from "zod";
import { registerTool } from "../../toolRegistry";
import { runTool, toolQuery } from "../_shared";
import { getAnalyticsCtx } from "./_context";

registerTool({
	name: "get_briefing",
	layer: "analytics",
	permission: null,
	confirmation: "none",
	costClass: "cheap",
	instruction: {
		whenToCall:
			"Use to answer 'show me my briefing' / 'what's the daily briefing?' / 'org weekly insight'. Returns the cached structured briefing (summary + highlights + action items) generated by the nightly briefing cron. No LLM cost on the read path — the briefing is pre-built.",
		whenNotToCall:
			"Don't use to generate a fresh briefing — call refresh_briefing for that (rate-limited).",
		preflight: [],
		synonyms: ["briefing", "daily digest", "weekly insight", "summary of today", "what's new"],
		goodExample: {
			description: "User asks 'show me my morning briefing'",
			args: { scope: "daily" },
		},
	},
	description: "Stub — overridden by buildToolDescription via instruction.",
	runbook: {
		onSuccess:
			"Surface the summary + highlights as plain prose. Don't over-format — the briefing is meant to be read, not skimmed.",
		onEmpty:
			"Tell the user the briefing hasn't been generated yet — the daily cron runs at 06:00 user-local. Offer to refresh_briefing if they have permission.",
	},
	example: { scope: "daily" },
	schema: z.object({
		scope: z.enum(["daily", "weekly"]).default("daily"),
	}),
	execute: async ({ scope }) =>
		runTool(async () => {
			const tc = getAnalyticsCtx();
			const path =
				scope === "weekly"
					? "ai/briefingsPublic:thisWeekForOrg"
					: "ai/briefingsPublic:todayForUser";
			const briefing = (await toolQuery(tc, path, { orgId: tc.orgId })) as {
				_id: string;
				summary?: string;
				payload?: {
					summary?: string;
					highlights?: string[];
					actionItems?: Array<{ label: string; intent?: string }>;
				};
				generatedAt: number;
			} | null;

			const data: {
				scope: "daily" | "weekly";
				briefing: typeof briefing;
			} = { scope, briefing };

			if (!briefing) {
				return {
					ok: true as const,
					data,
					display: {
						kind: "text" as const,
						text:
							scope === "weekly"
								? "No weekly insight available yet. The cron runs every Sunday."
								: "No daily briefing available yet. The cron runs every morning, or you can call refresh_briefing.",
					},
				};
			}

			const headline = briefing.payload?.summary ?? briefing.summary ?? "Briefing available.";
			return {
				ok: true as const,
				data,
				display: {
					kind: "text" as const,
					text: headline,
				},
			};
		}),
});
