/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as ResendOTP from "../ResendOTP.js";
import type * as ResendOTPPasswordReset from "../ResendOTPPasswordReset.js";
import type * as _functions_admin from "../_functions/admin.js";
import type * as _functions_authenticated from "../_functions/authenticated.js";
import type * as _migrations_2026_05_21_invitationRoleToRoleId from "../_migrations/2026_05_21_invitationRoleToRoleId.js";
import type * as _migrations_2026_05_22_addOrgSettingsDashboardAndTrash from "../_migrations/2026_05_22_addOrgSettingsDashboardAndTrash.js";
import type * as _migrations_2026_05_22_renameRealEstateTemplateIds from "../_migrations/2026_05_22_renameRealEstateTemplateIds.js";
import type * as _migrations_2026_05_23_addBriefingScopeAndPayload from "../_migrations/2026_05_23_addBriefingScopeAndPayload.js";
import type * as _migrations_2026_05_23_aiPermissionsBackfill from "../_migrations/2026_05_23_aiPermissionsBackfill.js";
import type * as _migrations_2026_05_23_backfillAiThinkingState from "../_migrations/2026_05_23_backfillAiThinkingState.js";
import type * as _migrations_2026_05_23_seedPlatformContext from "../_migrations/2026_05_23_seedPlatformContext.js";
import type * as _migrations_2026_05_23_setSuperAdmin from "../_migrations/2026_05_23_setSuperAdmin.js";
import type * as _migrations_2026_05_23_updateAIPlatformContext from "../_migrations/2026_05_23_updateAIPlatformContext.js";
import type * as _migrations_2026_05_24_addContextBagAndSubagent from "../_migrations/2026_05_24_addContextBagAndSubagent.js";
import type * as _migrations_2026_05_24_dedupeFieldDefinitions from "../_migrations/2026_05_24_dedupeFieldDefinitions.js";
import type * as _migrations_2026_05_24_dropOrgAiContext from "../_migrations/2026_05_24_dropOrgAiContext.js";
import type * as _migrations_2026_05_26_addAiDashboardWidgets from "../_migrations/2026_05_26_addAiDashboardWidgets.js";
import type * as _migrations_2026_05_26_normalizeDashboardMetrics from "../_migrations/2026_05_26_normalizeDashboardMetrics.js";
import type * as _migrations_2026_05_27_addAiMorningBriefingMetric from "../_migrations/2026_05_27_addAiMorningBriefingMetric.js";
import type * as _migrations_2026_05_27_addAiNextActions from "../_migrations/2026_05_27_addAiNextActions.js";
import type * as _migrations_2026_05_27_dropRemindersTable from "../_migrations/2026_05_27_dropRemindersTable.js";
import type * as _migrations_2026_05_27_renameAutoFollowupOnStageMove from "../_migrations/2026_05_27_renameAutoFollowupOnStageMove.js";
import type * as _migrations_2026_05_27_renameReminderNotificationKeys from "../_migrations/2026_05_27_renameReminderNotificationKeys.js";
import type * as _migrations_2026_05_27_seedIndustryTemplatesIntoDB from "../_migrations/2026_05_27_seedIndustryTemplatesIntoDB.js";
import type * as _migrations_2026_05_27_seedPlanLimitsExtensions from "../_migrations/2026_05_27_seedPlanLimitsExtensions.js";
import type * as _migrations_2026_05_27_seedPlatformTiers from "../_migrations/2026_05_27_seedPlatformTiers.js";
import type * as _migrations_2026_05_27_seedReservedSlugs from "../_migrations/2026_05_27_seedReservedSlugs.js";
import type * as _migrations_2026_05_28_addAiAnalyticsTables from "../_migrations/2026_05_28_addAiAnalyticsTables.js";
import type * as _migrations_2026_05_28_addPipelineVelocityWidget from "../_migrations/2026_05_28_addPipelineVelocityWidget.js";
import type * as _migrations_2026_05_28_addStandingOrderFirstFireAt from "../_migrations/2026_05_28_addStandingOrderFirstFireAt.js";
import type * as _migrations_2026_05_28_aiStandingOrders from "../_migrations/2026_05_28_aiStandingOrders.js";
import type * as _migrations_2026_05_29_renamePipelineVelocityToSalesPanel from "../_migrations/2026_05_29_renamePipelineVelocityToSalesPanel.js";
import type * as _migrations_2026_05_30_backfillDashboardLayoutFromTemplate from "../_migrations/2026_05_30_backfillDashboardLayoutFromTemplate.js";
import type * as _migrations_2026_05_30_clearMockDataDismissedAt from "../_migrations/2026_05_30_clearMockDataDismissedAt.js";
import type * as _migrations_2026_06_04_approvalsToAutonomy from "../_migrations/2026_06_04_approvalsToAutonomy.js";
import type * as _migrations_2026_06_05_seedDefaultWhatsappTemplates from "../_migrations/2026_06_05_seedDefaultWhatsappTemplates.js";
import type * as _migrations_2026_06_06_backfillRecordsViewAll from "../_migrations/2026_06_06_backfillRecordsViewAll.js";
import type * as _migrations_addDefaultStage from "../_migrations/addDefaultStage.js";
import type * as _migrations_addNotesColorAndType from "../_migrations/addNotesColorAndType.js";
import type * as _migrations_allowAudioUploads from "../_migrations/allowAudioUploads.js";
import type * as _migrations_consolidatePersonConversations from "../_migrations/consolidatePersonConversations.js";
import type * as _migrations_fixCompanyAssignedToColumnKey from "../_migrations/fixCompanyAssignedToColumnKey.js";
import type * as _migrations_markOnboardedFromMembership from "../_migrations/markOnboardedFromMembership.js";
import type * as _migrations_pinDealFieldsToDefaultStage from "../_migrations/pinDealFieldsToDefaultStage.js";
import type * as _migrations_recomputeOrgStats from "../_migrations/recomputeOrgStats.js";
import type * as _migrations_renameRealEstateToDubai from "../_migrations/renameRealEstateToDubai.js";
import type * as _migrations_seedNoteCategories from "../_migrations/seedNoteCategories.js";
import type * as _migrations_seedSortOrder from "../_migrations/seedSortOrder.js";
import type * as _migrations_seedTemplateDefaults from "../_migrations/seedTemplateDefaults.js";
import type * as _migrations_setOrgDefaultCurrency from "../_migrations/setOrgDefaultCurrency.js";
import type * as _migrations_setOrgPlan from "../_migrations/setOrgPlan.js";
import type * as _platform_aiKeys_actions from "../_platform/aiKeys/actions.js";
import type * as _platform_aiKeys_mutations from "../_platform/aiKeys/mutations.js";
import type * as _platform_aiKeys_queries from "../_platform/aiKeys/queries.js";
import type * as _platform_audit_helpers from "../_platform/audit/helpers.js";
import type * as _platform_audit_queries from "../_platform/audit/queries.js";
import type * as _platform_auth_queries from "../_platform/auth/queries.js";
import type * as _platform_billing_queries from "../_platform/billing/queries.js";
import type * as _platform_flags_mutations from "../_platform/flags/mutations.js";
import type * as _platform_flags_queries from "../_platform/flags/queries.js";
import type * as _platform_industries_builtIns_agency_freelance from "../_platform/industries/builtIns/agency_freelance.js";
import type * as _platform_industries_builtIns_b2b_saas from "../_platform/industries/builtIns/b2b_saas.js";
import type * as _platform_industries_builtIns_dubai_real_estate from "../_platform/industries/builtIns/dubai_real_estate.js";
import type * as _platform_industries_builtIns_freelancer from "../_platform/industries/builtIns/freelancer.js";
import type * as _platform_industries_builtIns_generic from "../_platform/industries/builtIns/generic.js";
import type * as _platform_industries_builtIns_index from "../_platform/industries/builtIns/index.js";
import type * as _platform_industries_builtIns_productivity from "../_platform/industries/builtIns/productivity.js";
import type * as _platform_industries_builtIns_real_estate from "../_platform/industries/builtIns/real_estate.js";
import type * as _platform_industries_builtIns_real_estate_saudi from "../_platform/industries/builtIns/real_estate_saudi.js";
import type * as _platform_industries_builtIns_recruiting from "../_platform/industries/builtIns/recruiting.js";
import type * as _platform_industries_mockData_agency_freelance from "../_platform/industries/mockData/agency_freelance.js";
import type * as _platform_industries_mockData_b2b_saas from "../_platform/industries/mockData/b2b_saas.js";
import type * as _platform_industries_mockData_dubai_real_estate from "../_platform/industries/mockData/dubai_real_estate.js";
import type * as _platform_industries_mockData_freelancer from "../_platform/industries/mockData/freelancer.js";
import type * as _platform_industries_mockData_generic from "../_platform/industries/mockData/generic.js";
import type * as _platform_industries_mockData_productivity from "../_platform/industries/mockData/productivity.js";
import type * as _platform_industries_mockData_real_estate from "../_platform/industries/mockData/real_estate.js";
import type * as _platform_industries_mockData_real_estate_saudi from "../_platform/industries/mockData/real_estate_saudi.js";
import type * as _platform_industries_mockData_recruiting from "../_platform/industries/mockData/recruiting.js";
import type * as _platform_industries_mutations from "../_platform/industries/mutations.js";
import type * as _platform_industries_queries from "../_platform/industries/queries.js";
import type * as _platform_industries_validators from "../_platform/industries/validators.js";
import type * as _platform_limits from "../_platform/limits.js";
import type * as _platform_orgs_mutations from "../_platform/orgs/mutations.js";
import type * as _platform_orgs_queries from "../_platform/orgs/queries.js";
import type * as _platform_otp_actions from "../_platform/otp/actions.js";
import type * as _platform_otp_mutations from "../_platform/otp/mutations.js";
import type * as _platform_otp_queries from "../_platform/otp/queries.js";
import type * as _platform_overview_queries from "../_platform/overview/queries.js";
import type * as _platform_ownerAuth from "../_platform/ownerAuth.js";
import type * as _platform_platformContext_mutations from "../_platform/platformContext/mutations.js";
import type * as _platform_platformContext_queries from "../_platform/platformContext/queries.js";
import type * as _platform_reservedSlugs_mutations from "../_platform/reservedSlugs/mutations.js";
import type * as _platform_reservedSlugs_queries from "../_platform/reservedSlugs/queries.js";
import type * as _platform_tiers_mutations from "../_platform/tiers/mutations.js";
import type * as _platform_tiers_queries from "../_platform/tiers/queries.js";
import type * as _platform_users_mutations from "../_platform/users/mutations.js";
import type * as _platform_users_queries from "../_platform/users/queries.js";
import type * as _platform_whatsappTemplates_mutations from "../_platform/whatsappTemplates/mutations.js";
import type * as _platform_whatsappTemplates_queries from "../_platform/whatsappTemplates/queries.js";
import type * as _shared_aiEntityPatch from "../_shared/aiEntityPatch.js";
import type * as _shared_constants from "../_shared/constants.js";
import type * as _shared_csvEncodingDetect from "../_shared/csvEncodingDetect.js";
import type * as _shared_dashboardDensity from "../_shared/dashboardDensity.js";
import type * as _shared_dedup from "../_shared/dedup.js";
import type * as _shared_enforcePlanLimit from "../_shared/enforcePlanLimit.js";
import type * as _shared_enrichmentErrorMap from "../_shared/enrichmentErrorMap.js";
import type * as _shared_entityCodes from "../_shared/entityCodes.js";
import type * as _shared_errors from "../_shared/errors.js";
import type * as _shared_fieldUpdateLog from "../_shared/fieldUpdateLog.js";
import type * as _shared_notificationKeys from "../_shared/notificationKeys.js";
import type * as _shared_orgStats from "../_shared/orgStats.js";
import type * as _shared_permissions_catalog from "../_shared/permissions/catalog.js";
import type * as _shared_permissions_derive from "../_shared/permissions/derive.js";
import type * as _shared_permissions_helpers from "../_shared/permissions/helpers.js";
import type * as _shared_permissions_index from "../_shared/permissions/index.js";
import type * as _shared_permissions_recordScope from "../_shared/permissions/recordScope.js";
import type * as _shared_rateLimit from "../_shared/rateLimit.js";
import type * as _shared_rateLimitMutation from "../_shared/rateLimitMutation.js";
import type * as _shared_recordCodes from "../_shared/recordCodes.js";
import type * as _shared_reservedSlugs from "../_shared/reservedSlugs.js";
import type * as _shared_sanitiseExtractedText from "../_shared/sanitiseExtractedText.js";
import type * as _shared_synonyms from "../_shared/synonyms.js";
import type * as _shared_types from "../_shared/types.js";
import type * as _shared_validators from "../_shared/validators.js";
import type * as _shared_widgetRegistry from "../_shared/widgetRegistry.js";
import type * as _test_helpers from "../_test/helpers.js";
import type * as activityLogs_helpers from "../activityLogs/helpers.js";
import type * as activityLogs_mutations from "../activityLogs/mutations.js";
import type * as ai__logAIActivityInternal from "../ai/_logAIActivityInternal.js";
import type * as ai_actions_analyzeDealClose from "../ai/actions/analyzeDealClose.js";
import type * as ai_actions_analyzeMetric from "../ai/actions/analyzeMetric.js";
import type * as ai_actions_draftMessage from "../ai/actions/draftMessage.js";
import type * as ai_actions_draftProposal from "../ai/actions/draftProposal.js";
import type * as ai_actions_rankNextActions from "../ai/actions/rankNextActions.js";
import type * as ai_actions_rebuildCohorts from "../ai/actions/rebuildCohorts.js";
import type * as ai_actions_summariseConversation from "../ai/actions/summariseConversation.js";
import type * as ai_actions_webScrape from "../ai/actions/webScrape.js";
import type * as ai_aiApiTokens from "../ai/aiApiTokens.js";
import type * as ai_aiEntityPatch from "../ai/aiEntityPatch.js";
import type * as ai_analytics_capabilities from "../ai/analytics/capabilities.js";
import type * as ai_analyzeMetricHelpers from "../ai/analyzeMetricHelpers.js";
import type * as ai_availableModels from "../ai/availableModels.js";
import type * as ai_briefings from "../ai/briefings.js";
import type * as ai_briefingsActions from "../ai/briefingsActions.js";
import type * as ai_briefingsPublic from "../ai/briefingsPublic.js";
import type * as ai_channels_capabilities from "../ai/channels/capabilities.js";
import type * as ai_channels_persona from "../ai/channels/persona.js";
import type * as ai_channels_personaCapability from "../ai/channels/personaCapability.js";
import type * as ai_channels_whatsappInbound from "../ai/channels/whatsappInbound.js";
import type * as ai_channels_whatsappOutbound from "../ai/channels/whatsappOutbound.js";
import type * as ai_channels_whatsappOutboundState from "../ai/channels/whatsappOutboundState.js";
import type * as ai_channels_whatsappTemplates from "../ai/channels/whatsappTemplates.js";
import type * as ai_chatAttachments from "../ai/chatAttachments.js";
import type * as ai_conversations from "../ai/conversations.js";
import type * as ai_creative_capabilities from "../ai/creative/capabilities.js";
import type * as ai_creativeHelpers from "../ai/creativeHelpers.js";
import type * as ai_csvImports from "../ai/csvImports.js";
import type * as ai_dealClose from "../ai/dealClose.js";
import type * as ai_encryption from "../ai/encryption.js";
import type * as ai_encryptionTypes from "../ai/encryptionTypes.js";
import type * as ai_insights_anomalies from "../ai/insights/anomalies.js";
import type * as ai_insights_anomalyDetection from "../ai/insights/anomalyDetection.js";
import type * as ai_insights_dealScores from "../ai/insights/dealScores.js";
import type * as ai_insights_dealScoring from "../ai/insights/dealScoring.js";
import type * as ai_insights_explainDealScore from "../ai/insights/explainDealScore.js";
import type * as ai_insights_explainDealScoreInternal from "../ai/insights/explainDealScoreInternal.js";
import type * as ai_interaction_capabilities from "../ai/interaction/capabilities.js";
import type * as ai_internal from "../ai/internal.js";
import type * as ai_keys from "../ai/keys.js";
import type * as ai_keysActions from "../ai/keysActions.js";
import type * as ai_messages from "../ai/messages.js";
import type * as ai_modelRegistry from "../ai/modelRegistry.js";
import type * as ai_models from "../ai/models.js";
import type * as ai_orchestrator_modelResolver from "../ai/orchestrator/modelResolver.js";
import type * as ai_orchestrator_quotaGate from "../ai/orchestrator/quotaGate.js";
import type * as ai_orchestrator_run from "../ai/orchestrator/run.js";
import type * as ai_personaContext from "../ai/personaContext.js";
import type * as ai_proactive_capabilities from "../ai/proactive/capabilities.js";
import type * as ai_processChat from "../ai/processChat.js";
import type * as ai_quarantined_capabilities from "../ai/quarantined/capabilities.js";
import type * as ai_quarantined_csvParser from "../ai/quarantined/csvParser.js";
import type * as ai_quarantined_csvParserInternal from "../ai/quarantined/csvParserInternal.js";
import type * as ai_quarantined_enrichmentProviders from "../ai/quarantined/enrichmentProviders.js";
import type * as ai_quarantined_enrichmentProvidersInternal from "../ai/quarantined/enrichmentProvidersInternal.js";
import type * as ai_quarantined_fileAnalyzer from "../ai/quarantined/fileAnalyzer.js";
import type * as ai_quarantined_fileAnalyzerInternal from "../ai/quarantined/fileAnalyzerInternal.js";
import type * as ai_queries_anomalies from "../ai/queries/anomalies.js";
import type * as ai_queries_auditFeed from "../ai/queries/auditFeed.js";
import type * as ai_queries_cascadeImpact from "../ai/queries/cascadeImpact.js";
import type * as ai_queries_cohorts from "../ai/queries/cohorts.js";
import type * as ai_queries_coverageReport from "../ai/queries/coverageReport.js";
import type * as ai_queries_insights from "../ai/queries/insights.js";
import type * as ai_queries_memberPerformance from "../ai/queries/memberPerformance.js";
import type * as ai_queries_nextActions from "../ai/queries/nextActions.js";
import type * as ai_queries_nextActionsTrigger from "../ai/queries/nextActionsTrigger.js";
import type * as ai_queries_pipelineVelocity from "../ai/queries/pipelineVelocity.js";
import type * as ai_queries_telemetry from "../ai/queries/telemetry.js";
import type * as ai_queries_tokenReport from "../ai/queries/tokenReport.js";
import type * as ai_queries_toolTrace from "../ai/queries/toolTrace.js";
import type * as ai_registry_audit from "../ai/registry/audit.js";
import type * as ai_registry_catalog from "../ai/registry/catalog.js";
import type * as ai_registry_coerce from "../ai/registry/coerce.js";
import type * as ai_registry_coverage from "../ai/registry/coverage.js";
import type * as ai_registry_define from "../ai/registry/define.js";
import type * as ai_registry_drive from "../ai/registry/drive.js";
import type * as ai_registry_gate from "../ai/registry/gate.js";
import type * as ai_registry_groups from "../ai/registry/groups.js";
import type * as ai_registry_modules from "../ai/registry/modules.js";
import type * as ai_registry_projectors_aiSdk from "../ai/registry/projectors/aiSdk.js";
import type * as ai_registry_projectors_dispatch from "../ai/registry/projectors/dispatch.js";
import type * as ai_registry_projectors_mcp from "../ai/registry/projectors/mcp.js";
import type * as ai_registry_projectors_rest from "../ai/registry/projectors/rest.js";
import type * as ai_registry_resolveRef from "../ai/registry/resolveRef.js";
import type * as ai_registry_result from "../ai/registry/result.js";
import type * as ai_registry_router from "../ai/registry/router.js";
import type * as ai_registry_types from "../ai/registry/types.js";
import type * as ai_registry_vertical from "../ai/registry/vertical.js";
import type * as ai_registry_wrapper from "../ai/registry/wrapper.js";
import type * as ai_runtime_autonomous from "../ai/runtime/autonomous.js";
import type * as ai_runtime_autonomousState from "../ai/runtime/autonomousState.js";
import type * as ai_runtime_coreTools from "../ai/runtime/coreTools.js";
import type * as ai_runtime_host from "../ai/runtime/host.js";
import type * as ai_runtime_nativeWebSearch from "../ai/runtime/nativeWebSearch.js";
import type * as ai_runtime_preflight from "../ai/runtime/preflight.js";
import type * as ai_standingOrders_evaluator from "../ai/standingOrders/evaluator.js";
import type * as ai_standingOrders_mutations from "../ai/standingOrders/mutations.js";
import type * as ai_standingOrders_queries from "../ai/standingOrders/queries.js";
import type * as ai_standingOrders_runner from "../ai/standingOrders/runner.js";
import type * as ai_standingOrders_schedule from "../ai/standingOrders/schedule.js";
import type * as ai_standingOrders_triggers from "../ai/standingOrders/triggers.js";
import type * as ai_suggestions from "../ai/suggestions.js";
import type * as ai_telemetry from "../ai/telemetry.js";
import type * as ai_titleGeneration from "../ai/titleGeneration.js";
import type * as ai_webSearchAction from "../ai/webSearchAction.js";
import type * as aiStepUp from "../aiStepUp.js";
import type * as auth from "../auth.js";
import type * as billing_actions from "../billing/actions.js";
import type * as billing_internal from "../billing/internal.js";
import type * as billing_queries from "../billing/queries.js";
import type * as contact from "../contact.js";
import type * as contactActions from "../contactActions.js";
import type * as crm_entities_companies_capabilities from "../crm/entities/companies/capabilities.js";
import type * as crm_entities_companies_mutations from "../crm/entities/companies/mutations.js";
import type * as crm_entities_companies_queries from "../crm/entities/companies/queries.js";
import type * as crm_entities_contacts_mutations from "../crm/entities/contacts/mutations.js";
import type * as crm_entities_contacts_queries from "../crm/entities/contacts/queries.js";
import type * as crm_entities_deals_capabilities from "../crm/entities/deals/capabilities.js";
import type * as crm_entities_deals_industryAnalytics from "../crm/entities/deals/industryAnalytics.js";
import type * as crm_entities_deals_mutations from "../crm/entities/deals/mutations.js";
import type * as crm_entities_deals_pipelineForecast from "../crm/entities/deals/pipelineForecast.js";
import type * as crm_entities_deals_queries from "../crm/entities/deals/queries.js";
import type * as crm_entities_leads_capabilities from "../crm/entities/leads/capabilities.js";
import type * as crm_entities_leads_mutations from "../crm/entities/leads/mutations.js";
import type * as crm_entities_leads_queries from "../crm/entities/leads/queries.js";
import type * as crm_fields_dedup_helpers from "../crm/fields/dedup/helpers.js";
import type * as crm_fields_fieldDefinitions_capabilities from "../crm/fields/fieldDefinitions/capabilities.js";
import type * as crm_fields_fieldDefinitions_internal from "../crm/fields/fieldDefinitions/internal.js";
import type * as crm_fields_fieldDefinitions_migrations from "../crm/fields/fieldDefinitions/migrations.js";
import type * as crm_fields_fieldDefinitions_mutations from "../crm/fields/fieldDefinitions/mutations.js";
import type * as crm_fields_fieldDefinitions_queries from "../crm/fields/fieldDefinitions/queries.js";
import type * as crm_fields_fieldValues_mutations from "../crm/fields/fieldValues/mutations.js";
import type * as crm_fields_fieldValues_queries from "../crm/fields/fieldValues/queries.js";
import type * as crm_fields_pipelines_capabilities from "../crm/fields/pipelines/capabilities.js";
import type * as crm_fields_pipelines_helpers from "../crm/fields/pipelines/helpers.js";
import type * as crm_fields_pipelines_mutations from "../crm/fields/pipelines/mutations.js";
import type * as crm_fields_pipelines_queries from "../crm/fields/pipelines/queries.js";
import type * as crm_fields_templates_mockSeeder from "../crm/fields/templates/mockSeeder.js";
import type * as crm_fields_templates_mutations from "../crm/fields/templates/mutations.js";
import type * as crm_fields_templates_queries from "../crm/fields/templates/queries.js";
import type * as crm_fields_templates_types from "../crm/fields/templates/types.js";
import type * as crm_people_queries from "../crm/people/queries.js";
import type * as crm_shared_bulk_capabilities from "../crm/shared/bulk/capabilities.js";
import type * as crm_shared_calendar_queries from "../crm/shared/calendar/queries.js";
import type * as crm_shared_conversations_internal from "../crm/shared/conversations/internal.js";
import type * as crm_shared_conversations_mutations from "../crm/shared/conversations/mutations.js";
import type * as crm_shared_conversations_queries from "../crm/shared/conversations/queries.js";
import type * as crm_shared_customFieldKeys from "../crm/shared/customFieldKeys.js";
import type * as crm_shared_messages_mutations from "../crm/shared/messages/mutations.js";
import type * as crm_shared_messages_queries from "../crm/shared/messages/queries.js";
import type * as crm_shared_noteCategories_capabilities from "../crm/shared/noteCategories/capabilities.js";
import type * as crm_shared_noteCategories_internal from "../crm/shared/noteCategories/internal.js";
import type * as crm_shared_noteCategories_mutations from "../crm/shared/noteCategories/mutations.js";
import type * as crm_shared_noteCategories_queries from "../crm/shared/noteCategories/queries.js";
import type * as crm_shared_notes_capabilities from "../crm/shared/notes/capabilities.js";
import type * as crm_shared_notes_mutations from "../crm/shared/notes/mutations.js";
import type * as crm_shared_notes_queries from "../crm/shared/notes/queries.js";
import type * as crm_shared_savedViews_capabilities from "../crm/shared/savedViews/capabilities.js";
import type * as crm_shared_savedViews_mutations from "../crm/shared/savedViews/mutations.js";
import type * as crm_shared_savedViews_queries from "../crm/shared/savedViews/queries.js";
import type * as crm_shared_tags_capabilities from "../crm/shared/tags/capabilities.js";
import type * as crm_shared_tags_internal from "../crm/shared/tags/internal.js";
import type * as crm_shared_tags_mutations from "../crm/shared/tags/mutations.js";
import type * as crm_shared_tags_queries from "../crm/shared/tags/queries.js";
import type * as crm_shared_tasks_capabilities from "../crm/shared/tasks/capabilities.js";
import type * as crm_shared_tasks_mutations from "../crm/shared/tasks/mutations.js";
import type * as crm_shared_tasks_queries from "../crm/shared/tasks/queries.js";
import type * as crm_shared_timeline_capabilities from "../crm/shared/timeline/capabilities.js";
import type * as crm_shared_timeline_queries from "../crm/shared/timeline/queries.js";
import type * as crons from "../crons.js";
import type * as dashboard_annotations_mutations from "../dashboard/annotations/mutations.js";
import type * as dashboard_annotations_queries from "../dashboard/annotations/queries.js";
import type * as dashboard_capabilities from "../dashboard/capabilities.js";
import type * as dashboard_dealScores_queries from "../dashboard/dealScores/queries.js";
import type * as dashboard_ephemeralCells_mutations from "../dashboard/ephemeralCells/mutations.js";
import type * as dashboard_ephemeralCells_queries from "../dashboard/ephemeralCells/queries.js";
import type * as featureFlags_queries from "../featureFlags/queries.js";
import type * as files_capabilities from "../files/capabilities.js";
import type * as files_mutations from "../files/mutations.js";
import type * as files_queries from "../files/queries.js";
import type * as gdpr_actions from "../gdpr/actions.js";
import type * as gdpr_internal from "../gdpr/internal.js";
import type * as http from "../http.js";
import type * as invitations_actions from "../invitations/actions.js";
import type * as invitations_index from "../invitations/index.js";
import type * as invitations_mutations from "../invitations/mutations.js";
import type * as invitations_queries from "../invitations/queries.js";
import type * as messaging_capabilities from "../messaging/capabilities.js";
import type * as notifications_capabilities from "../notifications/capabilities.js";
import type * as notifications_helpers from "../notifications/helpers.js";
import type * as notifications_mutations from "../notifications/mutations.js";
import type * as notifications_queries from "../notifications/queries.js";
import type * as orgRoles_index from "../orgRoles/index.js";
import type * as orgRoles_mutations from "../orgRoles/mutations.js";
import type * as orgRoles_queries from "../orgRoles/queries.js";
import type * as orgs_capabilities from "../orgs/capabilities.js";
import type * as orgs_helpers from "../orgs/helpers.js";
import type * as orgs_mutations from "../orgs/mutations.js";
import type * as orgs_queries from "../orgs/queries.js";
import type * as orgs_templates_fields from "../orgs/templates/fields.js";
import type * as orgs_templates_pipelineStages from "../orgs/templates/pipelineStages.js";
import type * as schema_ai from "../schema/ai.js";
import type * as schema_crmEntities from "../schema/crmEntities.js";
import type * as schema_crmFields from "../schema/crmFields.js";
import type * as schema_crmShared from "../schema/crmShared.js";
import type * as schema_identity from "../schema/identity.js";
import type * as schema_platform from "../schema/platform.js";
import type * as schema_system from "../schema/system.js";
import type * as trash_mutations from "../trash/mutations.js";
import type * as trash_queries from "../trash/queries.js";
import type * as users_helpers from "../users/helpers.js";
import type * as users_mutations from "../users/mutations.js";
import type * as users_queries from "../users/queries.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  ResendOTP: typeof ResendOTP;
  ResendOTPPasswordReset: typeof ResendOTPPasswordReset;
  "_functions/admin": typeof _functions_admin;
  "_functions/authenticated": typeof _functions_authenticated;
  "_migrations/2026_05_21_invitationRoleToRoleId": typeof _migrations_2026_05_21_invitationRoleToRoleId;
  "_migrations/2026_05_22_addOrgSettingsDashboardAndTrash": typeof _migrations_2026_05_22_addOrgSettingsDashboardAndTrash;
  "_migrations/2026_05_22_renameRealEstateTemplateIds": typeof _migrations_2026_05_22_renameRealEstateTemplateIds;
  "_migrations/2026_05_23_addBriefingScopeAndPayload": typeof _migrations_2026_05_23_addBriefingScopeAndPayload;
  "_migrations/2026_05_23_aiPermissionsBackfill": typeof _migrations_2026_05_23_aiPermissionsBackfill;
  "_migrations/2026_05_23_backfillAiThinkingState": typeof _migrations_2026_05_23_backfillAiThinkingState;
  "_migrations/2026_05_23_seedPlatformContext": typeof _migrations_2026_05_23_seedPlatformContext;
  "_migrations/2026_05_23_setSuperAdmin": typeof _migrations_2026_05_23_setSuperAdmin;
  "_migrations/2026_05_23_updateAIPlatformContext": typeof _migrations_2026_05_23_updateAIPlatformContext;
  "_migrations/2026_05_24_addContextBagAndSubagent": typeof _migrations_2026_05_24_addContextBagAndSubagent;
  "_migrations/2026_05_24_dedupeFieldDefinitions": typeof _migrations_2026_05_24_dedupeFieldDefinitions;
  "_migrations/2026_05_24_dropOrgAiContext": typeof _migrations_2026_05_24_dropOrgAiContext;
  "_migrations/2026_05_26_addAiDashboardWidgets": typeof _migrations_2026_05_26_addAiDashboardWidgets;
  "_migrations/2026_05_26_normalizeDashboardMetrics": typeof _migrations_2026_05_26_normalizeDashboardMetrics;
  "_migrations/2026_05_27_addAiMorningBriefingMetric": typeof _migrations_2026_05_27_addAiMorningBriefingMetric;
  "_migrations/2026_05_27_addAiNextActions": typeof _migrations_2026_05_27_addAiNextActions;
  "_migrations/2026_05_27_dropRemindersTable": typeof _migrations_2026_05_27_dropRemindersTable;
  "_migrations/2026_05_27_renameAutoFollowupOnStageMove": typeof _migrations_2026_05_27_renameAutoFollowupOnStageMove;
  "_migrations/2026_05_27_renameReminderNotificationKeys": typeof _migrations_2026_05_27_renameReminderNotificationKeys;
  "_migrations/2026_05_27_seedIndustryTemplatesIntoDB": typeof _migrations_2026_05_27_seedIndustryTemplatesIntoDB;
  "_migrations/2026_05_27_seedPlanLimitsExtensions": typeof _migrations_2026_05_27_seedPlanLimitsExtensions;
  "_migrations/2026_05_27_seedPlatformTiers": typeof _migrations_2026_05_27_seedPlatformTiers;
  "_migrations/2026_05_27_seedReservedSlugs": typeof _migrations_2026_05_27_seedReservedSlugs;
  "_migrations/2026_05_28_addAiAnalyticsTables": typeof _migrations_2026_05_28_addAiAnalyticsTables;
  "_migrations/2026_05_28_addPipelineVelocityWidget": typeof _migrations_2026_05_28_addPipelineVelocityWidget;
  "_migrations/2026_05_28_addStandingOrderFirstFireAt": typeof _migrations_2026_05_28_addStandingOrderFirstFireAt;
  "_migrations/2026_05_28_aiStandingOrders": typeof _migrations_2026_05_28_aiStandingOrders;
  "_migrations/2026_05_29_renamePipelineVelocityToSalesPanel": typeof _migrations_2026_05_29_renamePipelineVelocityToSalesPanel;
  "_migrations/2026_05_30_backfillDashboardLayoutFromTemplate": typeof _migrations_2026_05_30_backfillDashboardLayoutFromTemplate;
  "_migrations/2026_05_30_clearMockDataDismissedAt": typeof _migrations_2026_05_30_clearMockDataDismissedAt;
  "_migrations/2026_06_04_approvalsToAutonomy": typeof _migrations_2026_06_04_approvalsToAutonomy;
  "_migrations/2026_06_05_seedDefaultWhatsappTemplates": typeof _migrations_2026_06_05_seedDefaultWhatsappTemplates;
  "_migrations/2026_06_06_backfillRecordsViewAll": typeof _migrations_2026_06_06_backfillRecordsViewAll;
  "_migrations/addDefaultStage": typeof _migrations_addDefaultStage;
  "_migrations/addNotesColorAndType": typeof _migrations_addNotesColorAndType;
  "_migrations/allowAudioUploads": typeof _migrations_allowAudioUploads;
  "_migrations/consolidatePersonConversations": typeof _migrations_consolidatePersonConversations;
  "_migrations/fixCompanyAssignedToColumnKey": typeof _migrations_fixCompanyAssignedToColumnKey;
  "_migrations/markOnboardedFromMembership": typeof _migrations_markOnboardedFromMembership;
  "_migrations/pinDealFieldsToDefaultStage": typeof _migrations_pinDealFieldsToDefaultStage;
  "_migrations/recomputeOrgStats": typeof _migrations_recomputeOrgStats;
  "_migrations/renameRealEstateToDubai": typeof _migrations_renameRealEstateToDubai;
  "_migrations/seedNoteCategories": typeof _migrations_seedNoteCategories;
  "_migrations/seedSortOrder": typeof _migrations_seedSortOrder;
  "_migrations/seedTemplateDefaults": typeof _migrations_seedTemplateDefaults;
  "_migrations/setOrgDefaultCurrency": typeof _migrations_setOrgDefaultCurrency;
  "_migrations/setOrgPlan": typeof _migrations_setOrgPlan;
  "_platform/aiKeys/actions": typeof _platform_aiKeys_actions;
  "_platform/aiKeys/mutations": typeof _platform_aiKeys_mutations;
  "_platform/aiKeys/queries": typeof _platform_aiKeys_queries;
  "_platform/audit/helpers": typeof _platform_audit_helpers;
  "_platform/audit/queries": typeof _platform_audit_queries;
  "_platform/auth/queries": typeof _platform_auth_queries;
  "_platform/billing/queries": typeof _platform_billing_queries;
  "_platform/flags/mutations": typeof _platform_flags_mutations;
  "_platform/flags/queries": typeof _platform_flags_queries;
  "_platform/industries/builtIns/agency_freelance": typeof _platform_industries_builtIns_agency_freelance;
  "_platform/industries/builtIns/b2b_saas": typeof _platform_industries_builtIns_b2b_saas;
  "_platform/industries/builtIns/dubai_real_estate": typeof _platform_industries_builtIns_dubai_real_estate;
  "_platform/industries/builtIns/freelancer": typeof _platform_industries_builtIns_freelancer;
  "_platform/industries/builtIns/generic": typeof _platform_industries_builtIns_generic;
  "_platform/industries/builtIns/index": typeof _platform_industries_builtIns_index;
  "_platform/industries/builtIns/productivity": typeof _platform_industries_builtIns_productivity;
  "_platform/industries/builtIns/real_estate": typeof _platform_industries_builtIns_real_estate;
  "_platform/industries/builtIns/real_estate_saudi": typeof _platform_industries_builtIns_real_estate_saudi;
  "_platform/industries/builtIns/recruiting": typeof _platform_industries_builtIns_recruiting;
  "_platform/industries/mockData/agency_freelance": typeof _platform_industries_mockData_agency_freelance;
  "_platform/industries/mockData/b2b_saas": typeof _platform_industries_mockData_b2b_saas;
  "_platform/industries/mockData/dubai_real_estate": typeof _platform_industries_mockData_dubai_real_estate;
  "_platform/industries/mockData/freelancer": typeof _platform_industries_mockData_freelancer;
  "_platform/industries/mockData/generic": typeof _platform_industries_mockData_generic;
  "_platform/industries/mockData/productivity": typeof _platform_industries_mockData_productivity;
  "_platform/industries/mockData/real_estate": typeof _platform_industries_mockData_real_estate;
  "_platform/industries/mockData/real_estate_saudi": typeof _platform_industries_mockData_real_estate_saudi;
  "_platform/industries/mockData/recruiting": typeof _platform_industries_mockData_recruiting;
  "_platform/industries/mutations": typeof _platform_industries_mutations;
  "_platform/industries/queries": typeof _platform_industries_queries;
  "_platform/industries/validators": typeof _platform_industries_validators;
  "_platform/limits": typeof _platform_limits;
  "_platform/orgs/mutations": typeof _platform_orgs_mutations;
  "_platform/orgs/queries": typeof _platform_orgs_queries;
  "_platform/otp/actions": typeof _platform_otp_actions;
  "_platform/otp/mutations": typeof _platform_otp_mutations;
  "_platform/otp/queries": typeof _platform_otp_queries;
  "_platform/overview/queries": typeof _platform_overview_queries;
  "_platform/ownerAuth": typeof _platform_ownerAuth;
  "_platform/platformContext/mutations": typeof _platform_platformContext_mutations;
  "_platform/platformContext/queries": typeof _platform_platformContext_queries;
  "_platform/reservedSlugs/mutations": typeof _platform_reservedSlugs_mutations;
  "_platform/reservedSlugs/queries": typeof _platform_reservedSlugs_queries;
  "_platform/tiers/mutations": typeof _platform_tiers_mutations;
  "_platform/tiers/queries": typeof _platform_tiers_queries;
  "_platform/users/mutations": typeof _platform_users_mutations;
  "_platform/users/queries": typeof _platform_users_queries;
  "_platform/whatsappTemplates/mutations": typeof _platform_whatsappTemplates_mutations;
  "_platform/whatsappTemplates/queries": typeof _platform_whatsappTemplates_queries;
  "_shared/aiEntityPatch": typeof _shared_aiEntityPatch;
  "_shared/constants": typeof _shared_constants;
  "_shared/csvEncodingDetect": typeof _shared_csvEncodingDetect;
  "_shared/dashboardDensity": typeof _shared_dashboardDensity;
  "_shared/dedup": typeof _shared_dedup;
  "_shared/enforcePlanLimit": typeof _shared_enforcePlanLimit;
  "_shared/enrichmentErrorMap": typeof _shared_enrichmentErrorMap;
  "_shared/entityCodes": typeof _shared_entityCodes;
  "_shared/errors": typeof _shared_errors;
  "_shared/fieldUpdateLog": typeof _shared_fieldUpdateLog;
  "_shared/notificationKeys": typeof _shared_notificationKeys;
  "_shared/orgStats": typeof _shared_orgStats;
  "_shared/permissions/catalog": typeof _shared_permissions_catalog;
  "_shared/permissions/derive": typeof _shared_permissions_derive;
  "_shared/permissions/helpers": typeof _shared_permissions_helpers;
  "_shared/permissions/index": typeof _shared_permissions_index;
  "_shared/permissions/recordScope": typeof _shared_permissions_recordScope;
  "_shared/rateLimit": typeof _shared_rateLimit;
  "_shared/rateLimitMutation": typeof _shared_rateLimitMutation;
  "_shared/recordCodes": typeof _shared_recordCodes;
  "_shared/reservedSlugs": typeof _shared_reservedSlugs;
  "_shared/sanitiseExtractedText": typeof _shared_sanitiseExtractedText;
  "_shared/synonyms": typeof _shared_synonyms;
  "_shared/types": typeof _shared_types;
  "_shared/validators": typeof _shared_validators;
  "_shared/widgetRegistry": typeof _shared_widgetRegistry;
  "_test/helpers": typeof _test_helpers;
  "activityLogs/helpers": typeof activityLogs_helpers;
  "activityLogs/mutations": typeof activityLogs_mutations;
  "ai/_logAIActivityInternal": typeof ai__logAIActivityInternal;
  "ai/actions/analyzeDealClose": typeof ai_actions_analyzeDealClose;
  "ai/actions/analyzeMetric": typeof ai_actions_analyzeMetric;
  "ai/actions/draftMessage": typeof ai_actions_draftMessage;
  "ai/actions/draftProposal": typeof ai_actions_draftProposal;
  "ai/actions/rankNextActions": typeof ai_actions_rankNextActions;
  "ai/actions/rebuildCohorts": typeof ai_actions_rebuildCohorts;
  "ai/actions/summariseConversation": typeof ai_actions_summariseConversation;
  "ai/actions/webScrape": typeof ai_actions_webScrape;
  "ai/aiApiTokens": typeof ai_aiApiTokens;
  "ai/aiEntityPatch": typeof ai_aiEntityPatch;
  "ai/analytics/capabilities": typeof ai_analytics_capabilities;
  "ai/analyzeMetricHelpers": typeof ai_analyzeMetricHelpers;
  "ai/availableModels": typeof ai_availableModels;
  "ai/briefings": typeof ai_briefings;
  "ai/briefingsActions": typeof ai_briefingsActions;
  "ai/briefingsPublic": typeof ai_briefingsPublic;
  "ai/channels/capabilities": typeof ai_channels_capabilities;
  "ai/channels/persona": typeof ai_channels_persona;
  "ai/channels/personaCapability": typeof ai_channels_personaCapability;
  "ai/channels/whatsappInbound": typeof ai_channels_whatsappInbound;
  "ai/channels/whatsappOutbound": typeof ai_channels_whatsappOutbound;
  "ai/channels/whatsappOutboundState": typeof ai_channels_whatsappOutboundState;
  "ai/channels/whatsappTemplates": typeof ai_channels_whatsappTemplates;
  "ai/chatAttachments": typeof ai_chatAttachments;
  "ai/conversations": typeof ai_conversations;
  "ai/creative/capabilities": typeof ai_creative_capabilities;
  "ai/creativeHelpers": typeof ai_creativeHelpers;
  "ai/csvImports": typeof ai_csvImports;
  "ai/dealClose": typeof ai_dealClose;
  "ai/encryption": typeof ai_encryption;
  "ai/encryptionTypes": typeof ai_encryptionTypes;
  "ai/insights/anomalies": typeof ai_insights_anomalies;
  "ai/insights/anomalyDetection": typeof ai_insights_anomalyDetection;
  "ai/insights/dealScores": typeof ai_insights_dealScores;
  "ai/insights/dealScoring": typeof ai_insights_dealScoring;
  "ai/insights/explainDealScore": typeof ai_insights_explainDealScore;
  "ai/insights/explainDealScoreInternal": typeof ai_insights_explainDealScoreInternal;
  "ai/interaction/capabilities": typeof ai_interaction_capabilities;
  "ai/internal": typeof ai_internal;
  "ai/keys": typeof ai_keys;
  "ai/keysActions": typeof ai_keysActions;
  "ai/messages": typeof ai_messages;
  "ai/modelRegistry": typeof ai_modelRegistry;
  "ai/models": typeof ai_models;
  "ai/orchestrator/modelResolver": typeof ai_orchestrator_modelResolver;
  "ai/orchestrator/quotaGate": typeof ai_orchestrator_quotaGate;
  "ai/orchestrator/run": typeof ai_orchestrator_run;
  "ai/personaContext": typeof ai_personaContext;
  "ai/proactive/capabilities": typeof ai_proactive_capabilities;
  "ai/processChat": typeof ai_processChat;
  "ai/quarantined/capabilities": typeof ai_quarantined_capabilities;
  "ai/quarantined/csvParser": typeof ai_quarantined_csvParser;
  "ai/quarantined/csvParserInternal": typeof ai_quarantined_csvParserInternal;
  "ai/quarantined/enrichmentProviders": typeof ai_quarantined_enrichmentProviders;
  "ai/quarantined/enrichmentProvidersInternal": typeof ai_quarantined_enrichmentProvidersInternal;
  "ai/quarantined/fileAnalyzer": typeof ai_quarantined_fileAnalyzer;
  "ai/quarantined/fileAnalyzerInternal": typeof ai_quarantined_fileAnalyzerInternal;
  "ai/queries/anomalies": typeof ai_queries_anomalies;
  "ai/queries/auditFeed": typeof ai_queries_auditFeed;
  "ai/queries/cascadeImpact": typeof ai_queries_cascadeImpact;
  "ai/queries/cohorts": typeof ai_queries_cohorts;
  "ai/queries/coverageReport": typeof ai_queries_coverageReport;
  "ai/queries/insights": typeof ai_queries_insights;
  "ai/queries/memberPerformance": typeof ai_queries_memberPerformance;
  "ai/queries/nextActions": typeof ai_queries_nextActions;
  "ai/queries/nextActionsTrigger": typeof ai_queries_nextActionsTrigger;
  "ai/queries/pipelineVelocity": typeof ai_queries_pipelineVelocity;
  "ai/queries/telemetry": typeof ai_queries_telemetry;
  "ai/queries/tokenReport": typeof ai_queries_tokenReport;
  "ai/queries/toolTrace": typeof ai_queries_toolTrace;
  "ai/registry/audit": typeof ai_registry_audit;
  "ai/registry/catalog": typeof ai_registry_catalog;
  "ai/registry/coerce": typeof ai_registry_coerce;
  "ai/registry/coverage": typeof ai_registry_coverage;
  "ai/registry/define": typeof ai_registry_define;
  "ai/registry/drive": typeof ai_registry_drive;
  "ai/registry/gate": typeof ai_registry_gate;
  "ai/registry/groups": typeof ai_registry_groups;
  "ai/registry/modules": typeof ai_registry_modules;
  "ai/registry/projectors/aiSdk": typeof ai_registry_projectors_aiSdk;
  "ai/registry/projectors/dispatch": typeof ai_registry_projectors_dispatch;
  "ai/registry/projectors/mcp": typeof ai_registry_projectors_mcp;
  "ai/registry/projectors/rest": typeof ai_registry_projectors_rest;
  "ai/registry/resolveRef": typeof ai_registry_resolveRef;
  "ai/registry/result": typeof ai_registry_result;
  "ai/registry/router": typeof ai_registry_router;
  "ai/registry/types": typeof ai_registry_types;
  "ai/registry/vertical": typeof ai_registry_vertical;
  "ai/registry/wrapper": typeof ai_registry_wrapper;
  "ai/runtime/autonomous": typeof ai_runtime_autonomous;
  "ai/runtime/autonomousState": typeof ai_runtime_autonomousState;
  "ai/runtime/coreTools": typeof ai_runtime_coreTools;
  "ai/runtime/host": typeof ai_runtime_host;
  "ai/runtime/nativeWebSearch": typeof ai_runtime_nativeWebSearch;
  "ai/runtime/preflight": typeof ai_runtime_preflight;
  "ai/standingOrders/evaluator": typeof ai_standingOrders_evaluator;
  "ai/standingOrders/mutations": typeof ai_standingOrders_mutations;
  "ai/standingOrders/queries": typeof ai_standingOrders_queries;
  "ai/standingOrders/runner": typeof ai_standingOrders_runner;
  "ai/standingOrders/schedule": typeof ai_standingOrders_schedule;
  "ai/standingOrders/triggers": typeof ai_standingOrders_triggers;
  "ai/suggestions": typeof ai_suggestions;
  "ai/telemetry": typeof ai_telemetry;
  "ai/titleGeneration": typeof ai_titleGeneration;
  "ai/webSearchAction": typeof ai_webSearchAction;
  aiStepUp: typeof aiStepUp;
  auth: typeof auth;
  "billing/actions": typeof billing_actions;
  "billing/internal": typeof billing_internal;
  "billing/queries": typeof billing_queries;
  contact: typeof contact;
  contactActions: typeof contactActions;
  "crm/entities/companies/capabilities": typeof crm_entities_companies_capabilities;
  "crm/entities/companies/mutations": typeof crm_entities_companies_mutations;
  "crm/entities/companies/queries": typeof crm_entities_companies_queries;
  "crm/entities/contacts/mutations": typeof crm_entities_contacts_mutations;
  "crm/entities/contacts/queries": typeof crm_entities_contacts_queries;
  "crm/entities/deals/capabilities": typeof crm_entities_deals_capabilities;
  "crm/entities/deals/industryAnalytics": typeof crm_entities_deals_industryAnalytics;
  "crm/entities/deals/mutations": typeof crm_entities_deals_mutations;
  "crm/entities/deals/pipelineForecast": typeof crm_entities_deals_pipelineForecast;
  "crm/entities/deals/queries": typeof crm_entities_deals_queries;
  "crm/entities/leads/capabilities": typeof crm_entities_leads_capabilities;
  "crm/entities/leads/mutations": typeof crm_entities_leads_mutations;
  "crm/entities/leads/queries": typeof crm_entities_leads_queries;
  "crm/fields/dedup/helpers": typeof crm_fields_dedup_helpers;
  "crm/fields/fieldDefinitions/capabilities": typeof crm_fields_fieldDefinitions_capabilities;
  "crm/fields/fieldDefinitions/internal": typeof crm_fields_fieldDefinitions_internal;
  "crm/fields/fieldDefinitions/migrations": typeof crm_fields_fieldDefinitions_migrations;
  "crm/fields/fieldDefinitions/mutations": typeof crm_fields_fieldDefinitions_mutations;
  "crm/fields/fieldDefinitions/queries": typeof crm_fields_fieldDefinitions_queries;
  "crm/fields/fieldValues/mutations": typeof crm_fields_fieldValues_mutations;
  "crm/fields/fieldValues/queries": typeof crm_fields_fieldValues_queries;
  "crm/fields/pipelines/capabilities": typeof crm_fields_pipelines_capabilities;
  "crm/fields/pipelines/helpers": typeof crm_fields_pipelines_helpers;
  "crm/fields/pipelines/mutations": typeof crm_fields_pipelines_mutations;
  "crm/fields/pipelines/queries": typeof crm_fields_pipelines_queries;
  "crm/fields/templates/mockSeeder": typeof crm_fields_templates_mockSeeder;
  "crm/fields/templates/mutations": typeof crm_fields_templates_mutations;
  "crm/fields/templates/queries": typeof crm_fields_templates_queries;
  "crm/fields/templates/types": typeof crm_fields_templates_types;
  "crm/people/queries": typeof crm_people_queries;
  "crm/shared/bulk/capabilities": typeof crm_shared_bulk_capabilities;
  "crm/shared/calendar/queries": typeof crm_shared_calendar_queries;
  "crm/shared/conversations/internal": typeof crm_shared_conversations_internal;
  "crm/shared/conversations/mutations": typeof crm_shared_conversations_mutations;
  "crm/shared/conversations/queries": typeof crm_shared_conversations_queries;
  "crm/shared/customFieldKeys": typeof crm_shared_customFieldKeys;
  "crm/shared/messages/mutations": typeof crm_shared_messages_mutations;
  "crm/shared/messages/queries": typeof crm_shared_messages_queries;
  "crm/shared/noteCategories/capabilities": typeof crm_shared_noteCategories_capabilities;
  "crm/shared/noteCategories/internal": typeof crm_shared_noteCategories_internal;
  "crm/shared/noteCategories/mutations": typeof crm_shared_noteCategories_mutations;
  "crm/shared/noteCategories/queries": typeof crm_shared_noteCategories_queries;
  "crm/shared/notes/capabilities": typeof crm_shared_notes_capabilities;
  "crm/shared/notes/mutations": typeof crm_shared_notes_mutations;
  "crm/shared/notes/queries": typeof crm_shared_notes_queries;
  "crm/shared/savedViews/capabilities": typeof crm_shared_savedViews_capabilities;
  "crm/shared/savedViews/mutations": typeof crm_shared_savedViews_mutations;
  "crm/shared/savedViews/queries": typeof crm_shared_savedViews_queries;
  "crm/shared/tags/capabilities": typeof crm_shared_tags_capabilities;
  "crm/shared/tags/internal": typeof crm_shared_tags_internal;
  "crm/shared/tags/mutations": typeof crm_shared_tags_mutations;
  "crm/shared/tags/queries": typeof crm_shared_tags_queries;
  "crm/shared/tasks/capabilities": typeof crm_shared_tasks_capabilities;
  "crm/shared/tasks/mutations": typeof crm_shared_tasks_mutations;
  "crm/shared/tasks/queries": typeof crm_shared_tasks_queries;
  "crm/shared/timeline/capabilities": typeof crm_shared_timeline_capabilities;
  "crm/shared/timeline/queries": typeof crm_shared_timeline_queries;
  crons: typeof crons;
  "dashboard/annotations/mutations": typeof dashboard_annotations_mutations;
  "dashboard/annotations/queries": typeof dashboard_annotations_queries;
  "dashboard/capabilities": typeof dashboard_capabilities;
  "dashboard/dealScores/queries": typeof dashboard_dealScores_queries;
  "dashboard/ephemeralCells/mutations": typeof dashboard_ephemeralCells_mutations;
  "dashboard/ephemeralCells/queries": typeof dashboard_ephemeralCells_queries;
  "featureFlags/queries": typeof featureFlags_queries;
  "files/capabilities": typeof files_capabilities;
  "files/mutations": typeof files_mutations;
  "files/queries": typeof files_queries;
  "gdpr/actions": typeof gdpr_actions;
  "gdpr/internal": typeof gdpr_internal;
  http: typeof http;
  "invitations/actions": typeof invitations_actions;
  "invitations/index": typeof invitations_index;
  "invitations/mutations": typeof invitations_mutations;
  "invitations/queries": typeof invitations_queries;
  "messaging/capabilities": typeof messaging_capabilities;
  "notifications/capabilities": typeof notifications_capabilities;
  "notifications/helpers": typeof notifications_helpers;
  "notifications/mutations": typeof notifications_mutations;
  "notifications/queries": typeof notifications_queries;
  "orgRoles/index": typeof orgRoles_index;
  "orgRoles/mutations": typeof orgRoles_mutations;
  "orgRoles/queries": typeof orgRoles_queries;
  "orgs/capabilities": typeof orgs_capabilities;
  "orgs/helpers": typeof orgs_helpers;
  "orgs/mutations": typeof orgs_mutations;
  "orgs/queries": typeof orgs_queries;
  "orgs/templates/fields": typeof orgs_templates_fields;
  "orgs/templates/pipelineStages": typeof orgs_templates_pipelineStages;
  "schema/ai": typeof schema_ai;
  "schema/crmEntities": typeof schema_crmEntities;
  "schema/crmFields": typeof schema_crmFields;
  "schema/crmShared": typeof schema_crmShared;
  "schema/identity": typeof schema_identity;
  "schema/platform": typeof schema_platform;
  "schema/system": typeof schema_system;
  "trash/mutations": typeof trash_mutations;
  "trash/queries": typeof trash_queries;
  "users/helpers": typeof users_helpers;
  "users/mutations": typeof users_mutations;
  "users/queries": typeof users_queries;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
