/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as ResendOTPPasswordReset from "../ResendOTPPasswordReset.js";
import type * as _functions_admin from "../_functions/admin.js";
import type * as _functions_authenticated from "../_functions/authenticated.js";
import type * as _migrations_2026_05_21_invitationRoleToRoleId from "../_migrations/2026_05_21_invitationRoleToRoleId.js";
import type * as _migrations_2026_05_22_addOrgSettingsDashboardAndTrash from "../_migrations/2026_05_22_addOrgSettingsDashboardAndTrash.js";
import type * as _migrations_2026_05_22_renameRealEstateTemplateIds from "../_migrations/2026_05_22_renameRealEstateTemplateIds.js";
import type * as _migrations_2026_05_23_addBriefingScopeAndPayload from "../_migrations/2026_05_23_addBriefingScopeAndPayload.js";
import type * as _migrations_2026_05_23_aiPermissionsBackfill from "../_migrations/2026_05_23_aiPermissionsBackfill.js";
import type * as _migrations_2026_05_23_backfillAiThinkingState from "../_migrations/2026_05_23_backfillAiThinkingState.js";
import type * as _migrations_2026_05_23_seedPlatformContext from "../_migrations/2026_05_23_seedPlatformContext.js";
import type * as _migrations_2026_05_23_setSuperAdmin from "../_migrations/2026_05_23_setSuperAdmin.js";
import type * as _migrations_2026_05_23_updateAIPlatformContext from "../_migrations/2026_05_23_updateAIPlatformContext.js";
import type * as _migrations_2026_05_24_addContextBagAndSubagent from "../_migrations/2026_05_24_addContextBagAndSubagent.js";
import type * as _migrations_2026_05_24_dedupeFieldDefinitions from "../_migrations/2026_05_24_dedupeFieldDefinitions.js";
import type * as _migrations_2026_05_24_dropOrgAiContext from "../_migrations/2026_05_24_dropOrgAiContext.js";
import type * as _migrations_2026_05_26_addAiDashboardWidgets from "../_migrations/2026_05_26_addAiDashboardWidgets.js";
import type * as _migrations_2026_05_26_normalizeDashboardMetrics from "../_migrations/2026_05_26_normalizeDashboardMetrics.js";
import type * as _migrations_2026_05_27_addAiMorningBriefingMetric from "../_migrations/2026_05_27_addAiMorningBriefingMetric.js";
import type * as _migrations_2026_05_27_addAiNextActions from "../_migrations/2026_05_27_addAiNextActions.js";
import type * as _migrations_2026_05_28_addAiAnalyticsTables from "../_migrations/2026_05_28_addAiAnalyticsTables.js";
import type * as _migrations_2026_05_28_addPipelineVelocityWidget from "../_migrations/2026_05_28_addPipelineVelocityWidget.js";
import type * as _migrations_2026_05_28_addStandingOrderFirstFireAt from "../_migrations/2026_05_28_addStandingOrderFirstFireAt.js";
import type * as _migrations_2026_05_28_aiStandingOrders from "../_migrations/2026_05_28_aiStandingOrders.js";
import type * as _migrations_addDefaultStage from "../_migrations/addDefaultStage.js";
import type * as _migrations_addNotesColorAndType from "../_migrations/addNotesColorAndType.js";
import type * as _migrations_allowAudioUploads from "../_migrations/allowAudioUploads.js";
import type * as _migrations_consolidatePersonConversations from "../_migrations/consolidatePersonConversations.js";
import type * as _migrations_fixCompanyAssignedToColumnKey from "../_migrations/fixCompanyAssignedToColumnKey.js";
import type * as _migrations_markOnboardedFromMembership from "../_migrations/markOnboardedFromMembership.js";
import type * as _migrations_pinDealFieldsToDefaultStage from "../_migrations/pinDealFieldsToDefaultStage.js";
import type * as _migrations_recomputeOrgStats from "../_migrations/recomputeOrgStats.js";
import type * as _migrations_renameRealEstateToDubai from "../_migrations/renameRealEstateToDubai.js";
import type * as _migrations_seedNoteCategories from "../_migrations/seedNoteCategories.js";
import type * as _migrations_seedSortOrder from "../_migrations/seedSortOrder.js";
import type * as _migrations_seedTemplateDefaults from "../_migrations/seedTemplateDefaults.js";
import type * as _migrations_setOrgDefaultCurrency from "../_migrations/setOrgDefaultCurrency.js";
import type * as _migrations_setOrgPlan from "../_migrations/setOrgPlan.js";
import type * as _migrations_tightenReminderSourceAndAddPriority from "../_migrations/tightenReminderSourceAndAddPriority.js";
import type * as _platform_limits from "../_platform/limits.js";
import type * as _shared_aiApprovals from "../_shared/aiApprovals.js";
import type * as _shared_aiEntityPatch from "../_shared/aiEntityPatch.js";
import type * as _shared_bulkProgress from "../_shared/bulkProgress.js";
import type * as _shared_constants from "../_shared/constants.js";
import type * as _shared_csvEncodingDetect from "../_shared/csvEncodingDetect.js";
import type * as _shared_dedup from "../_shared/dedup.js";
import type * as _shared_enforcePlanLimit from "../_shared/enforcePlanLimit.js";
import type * as _shared_enrichmentErrorMap from "../_shared/enrichmentErrorMap.js";
import type * as _shared_entityCodes from "../_shared/entityCodes.js";
import type * as _shared_errors from "../_shared/errors.js";
import type * as _shared_fieldUpdateLog from "../_shared/fieldUpdateLog.js";
import type * as _shared_notificationKeys from "../_shared/notificationKeys.js";
import type * as _shared_orgStats from "../_shared/orgStats.js";
import type * as _shared_permissions_catalog from "../_shared/permissions/catalog.js";
import type * as _shared_permissions_derive from "../_shared/permissions/derive.js";
import type * as _shared_permissions_helpers from "../_shared/permissions/helpers.js";
import type * as _shared_permissions_index from "../_shared/permissions/index.js";
import type * as _shared_rateLimit from "../_shared/rateLimit.js";
import type * as _shared_recordCodes from "../_shared/recordCodes.js";
import type * as _shared_reservedSlugs from "../_shared/reservedSlugs.js";
import type * as _shared_sanitiseExtractedText from "../_shared/sanitiseExtractedText.js";
import type * as _shared_synonyms from "../_shared/synonyms.js";
import type * as _shared_types from "../_shared/types.js";
import type * as _shared_validators from "../_shared/validators.js";
import type * as _shared_widgetRegistry from "../_shared/widgetRegistry.js";
import type * as _test_helpers from "../_test/helpers.js";
import type * as activityLogs_helpers from "../activityLogs/helpers.js";
import type * as activityLogs_mutations from "../activityLogs/mutations.js";
import type * as ai__logAIActivityInternal from "../ai/_logAIActivityInternal.js";
import type * as ai_actions_analyzeDealClose from "../ai/actions/analyzeDealClose.js";
import type * as ai_actions_analyzeMetric from "../ai/actions/analyzeMetric.js";
import type * as ai_actions_draftMessage from "../ai/actions/draftMessage.js";
import type * as ai_actions_draftProposal from "../ai/actions/draftProposal.js";
import type * as ai_actions_rankNextActions from "../ai/actions/rankNextActions.js";
import type * as ai_actions_rebuildCohorts from "../ai/actions/rebuildCohorts.js";
import type * as ai_actions_summariseConversation from "../ai/actions/summariseConversation.js";
import type * as ai_actions_webScrape from "../ai/actions/webScrape.js";
import type * as ai_aiEntityPatch from "../ai/aiEntityPatch.js";
import type * as ai_analyzeMetricHelpers from "../ai/analyzeMetricHelpers.js";
import type * as ai_availableModels from "../ai/availableModels.js";
import type * as ai_briefings from "../ai/briefings.js";
import type * as ai_briefingsActions from "../ai/briefingsActions.js";
import type * as ai_briefingsPublic from "../ai/briefingsPublic.js";
import type * as ai_chatAttachments from "../ai/chatAttachments.js";
import type * as ai_conversations from "../ai/conversations.js";
import type * as ai_creativeHelpers from "../ai/creativeHelpers.js";
import type * as ai_csvImports from "../ai/csvImports.js";
import type * as ai_dealClose from "../ai/dealClose.js";
import type * as ai_encryption from "../ai/encryption.js";
import type * as ai_encryptionTypes from "../ai/encryptionTypes.js";
import type * as ai_internal from "../ai/internal.js";
import type * as ai_keys from "../ai/keys.js";
import type * as ai_keysActions from "../ai/keysActions.js";
import type * as ai_messages from "../ai/messages.js";
import type * as ai_modelRegistry from "../ai/modelRegistry.js";
import type * as ai_models from "../ai/models.js";
import type * as ai_orchestrator_friendlyToolError from "../ai/orchestrator/friendlyToolError.js";
import type * as ai_orchestrator_modelResolver from "../ai/orchestrator/modelResolver.js";
import type * as ai_orchestrator_orgSchemaContext from "../ai/orchestrator/orgSchemaContext.js";
import type * as ai_orchestrator_quotaGate from "../ai/orchestrator/quotaGate.js";
import type * as ai_orchestrator_reasoningBuffer from "../ai/orchestrator/reasoningBuffer.js";
import type * as ai_orchestrator_resume from "../ai/orchestrator/resume.js";
import type * as ai_orchestrator_router from "../ai/orchestrator/router.js";
import type * as ai_orchestrator_run from "../ai/orchestrator/run.js";
import type * as ai_orchestrator_streamLoop from "../ai/orchestrator/streamLoop.js";
import type * as ai_orchestrator_suggestionGenerator from "../ai/orchestrator/suggestionGenerator.js";
import type * as ai_orchestrator_toolContextBinder from "../ai/orchestrator/toolContextBinder.js";
import type * as ai_orchestrator_twoStepSchemaAudit from "../ai/orchestrator/twoStepSchemaAudit.js";
import type * as ai_orchestrator_zodErrorFormatter from "../ai/orchestrator/zodErrorFormatter.js";
import type * as ai_personaContext from "../ai/personaContext.js";
import type * as ai_processChat from "../ai/processChat.js";
import type * as ai_quarantined_csvParser from "../ai/quarantined/csvParser.js";
import type * as ai_quarantined_csvParserInternal from "../ai/quarantined/csvParserInternal.js";
import type * as ai_quarantined_enrichmentProviders from "../ai/quarantined/enrichmentProviders.js";
import type * as ai_quarantined_enrichmentProvidersInternal from "../ai/quarantined/enrichmentProvidersInternal.js";
import type * as ai_quarantined_fileAnalyzer from "../ai/quarantined/fileAnalyzer.js";
import type * as ai_quarantined_fileAnalyzerInternal from "../ai/quarantined/fileAnalyzerInternal.js";
import type * as ai_queries_anomalies from "../ai/queries/anomalies.js";
import type * as ai_queries_cascadeImpact from "../ai/queries/cascadeImpact.js";
import type * as ai_queries_cohorts from "../ai/queries/cohorts.js";
import type * as ai_queries_insights from "../ai/queries/insights.js";
import type * as ai_queries_memberPerformance from "../ai/queries/memberPerformance.js";
import type * as ai_queries_nextActions from "../ai/queries/nextActions.js";
import type * as ai_queries_pipelineVelocity from "../ai/queries/pipelineVelocity.js";
import type * as ai_queries_telemetry from "../ai/queries/telemetry.js";
import type * as ai_queries_toolTrace from "../ai/queries/toolTrace.js";
import type * as ai_standingOrders_evaluator from "../ai/standingOrders/evaluator.js";
import type * as ai_standingOrders_mutations from "../ai/standingOrders/mutations.js";
import type * as ai_standingOrders_queries from "../ai/standingOrders/queries.js";
import type * as ai_standingOrders_runner from "../ai/standingOrders/runner.js";
import type * as ai_standingOrders_schedule from "../ai/standingOrders/schedule.js";
import type * as ai_standingOrders_triggers from "../ai/standingOrders/triggers.js";
import type * as ai_subagents_crmAction from "../ai/subagents/crmAction.js";
import type * as ai_subagents_csvImport from "../ai/subagents/csvImport.js";
import type * as ai_subagents_enrichment from "../ai/subagents/enrichment.js";
import type * as ai_subagents_index from "../ai/subagents/index.js";
import type * as ai_subagents_qa from "../ai/subagents/qa.js";
import type * as ai_subagents_settings from "../ai/subagents/settings.js";
import type * as ai_subagents_types from "../ai/subagents/types.js";
import type * as ai_suggestions from "../ai/suggestions.js";
import type * as ai_systemPrompt from "../ai/systemPrompt.js";
import type * as ai_telemetry from "../ai/telemetry.js";
import type * as ai_titleGeneration from "../ai/titleGeneration.js";
import type * as ai_toolRegistry from "../ai/toolRegistry.js";
import type * as ai_tools__shared from "../ai/tools/_shared.js";
import type * as ai_tools_analytics__context from "../ai/tools/analytics/_context.js";
import type * as ai_tools_analytics_analyzeMetric from "../ai/tools/analytics/analyzeMetric.js";
import type * as ai_tools_analytics_cohortAnalysis from "../ai/tools/analytics/cohortAnalysis.js";
import type * as ai_tools_analytics_getBriefing from "../ai/tools/analytics/getBriefing.js";
import type * as ai_tools_analytics_index from "../ai/tools/analytics/index.js";
import type * as ai_tools_analytics_memberPerformance from "../ai/tools/analytics/memberPerformance.js";
import type * as ai_tools_analytics_refreshBriefing from "../ai/tools/analytics/refreshBriefing.js";
import type * as ai_tools_companies__context from "../ai/tools/companies/_context.js";
import type * as ai_tools_companies_addPerson from "../ai/tools/companies/addPerson.js";
import type * as ai_tools_companies_index from "../ai/tools/companies/index.js";
import type * as ai_tools_companies_removePerson from "../ai/tools/companies/removePerson.js";
import type * as ai_tools_contextBag from "../ai/tools/contextBag.js";
import type * as ai_tools_creative__context from "../ai/tools/creative/_context.js";
import type * as ai_tools_creative_draftMessage from "../ai/tools/creative/draftMessage.js";
import type * as ai_tools_creative_draftProposal from "../ai/tools/creative/draftProposal.js";
import type * as ai_tools_creative_index from "../ai/tools/creative/index.js";
import type * as ai_tools_creative_summariseConversation from "../ai/tools/creative/summariseConversation.js";
import type * as ai_tools_creative_webScrape from "../ai/tools/creative/webScrape.js";
import type * as ai_tools_crud__context from "../ai/tools/crud/_context.js";
import type * as ai_tools_crud_convertLead from "../ai/tools/crud/convertLead.js";
import type * as ai_tools_crud_createCompany from "../ai/tools/crud/createCompany.js";
import type * as ai_tools_crud_createContact from "../ai/tools/crud/createContact.js";
import type * as ai_tools_crud_createDeal from "../ai/tools/crud/createDeal.js";
import type * as ai_tools_crud_createLead from "../ai/tools/crud/createLead.js";
import type * as ai_tools_crud_deleteEntity from "../ai/tools/crud/deleteEntity.js";
import type * as ai_tools_crud_index from "../ai/tools/crud/index.js";
import type * as ai_tools_crud_revertContact from "../ai/tools/crud/revertContact.js";
import type * as ai_tools_files__context from "../ai/tools/files/_context.js";
import type * as ai_tools_files_index from "../ai/tools/files/index.js";
import type * as ai_tools_files_listFiles from "../ai/tools/files/listFiles.js";
import type * as ai_tools_files_removeFile from "../ai/tools/files/removeFile.js";
import type * as ai_tools_files_updateFileTags from "../ai/tools/files/updateFileTags.js";
import type * as ai_tools_interaction_askChoice from "../ai/tools/interaction/askChoice.js";
import type * as ai_tools_interaction_askInput from "../ai/tools/interaction/askInput.js";
import type * as ai_tools_introspect from "../ai/tools/introspect.js";
import type * as ai_tools_layers__index from "../ai/tools/layers/_index.js";
import type * as ai_tools_layers_bulk from "../ai/tools/layers/bulk.js";
import type * as ai_tools_layers_categories from "../ai/tools/layers/categories.js";
import type * as ai_tools_layers_csvImport from "../ai/tools/layers/csvImport.js";
import type * as ai_tools_layers_csvImportInternal from "../ai/tools/layers/csvImportInternal.js";
import type * as ai_tools_layers_data from "../ai/tools/layers/data.js";
import type * as ai_tools_layers_enrichment from "../ai/tools/layers/enrichment.js";
import type * as ai_tools_layers_enrichmentInternal from "../ai/tools/layers/enrichmentInternal.js";
import type * as ai_tools_layers_fields from "../ai/tools/layers/fields.js";
import type * as ai_tools_layers_fileAnalysis from "../ai/tools/layers/fileAnalysis.js";
import type * as ai_tools_layers_members from "../ai/tools/layers/members.js";
import type * as ai_tools_layers_pipelines from "../ai/tools/layers/pipelines.js";
import type * as ai_tools_layers_settings from "../ai/tools/layers/settings.js";
import type * as ai_tools_layers_tags from "../ai/tools/layers/tags.js";
import type * as ai_tools_layers_templates from "../ai/tools/layers/templates.js";
import type * as ai_tools_layers_views from "../ai/tools/layers/views.js";
import type * as ai_tools_messaging__context from "../ai/tools/messaging/_context.js";
import type * as ai_tools_messaging_addParticipants from "../ai/tools/messaging/addParticipants.js";
import type * as ai_tools_messaging_index from "../ai/tools/messaging/index.js";
import type * as ai_tools_messaging_listMessages from "../ai/tools/messaging/listMessages.js";
import type * as ai_tools_messaging_markThreadRead from "../ai/tools/messaging/markThreadRead.js";
import type * as ai_tools_messaging_removeParticipant from "../ai/tools/messaging/removeParticipant.js";
import type * as ai_tools_messaging_sendMessage from "../ai/tools/messaging/sendMessage.js";
import type * as ai_tools_notes__context from "../ai/tools/notes/_context.js";
import type * as ai_tools_notes_deleteNote from "../ai/tools/notes/deleteNote.js";
import type * as ai_tools_notes_index from "../ai/tools/notes/index.js";
import type * as ai_tools_notes_pinNote from "../ai/tools/notes/pinNote.js";
import type * as ai_tools_notes_setNoteCategory from "../ai/tools/notes/setNoteCategory.js";
import type * as ai_tools_notes_updateNote from "../ai/tools/notes/updateNote.js";
import type * as ai_tools_notesReminders from "../ai/tools/notesReminders.js";
import type * as ai_tools_notifications__context from "../ai/tools/notifications/_context.js";
import type * as ai_tools_notifications_index from "../ai/tools/notifications/index.js";
import type * as ai_tools_notifications_listNotifications from "../ai/tools/notifications/listNotifications.js";
import type * as ai_tools_notifications_markNotificationRead from "../ai/tools/notifications/markNotificationRead.js";
import type * as ai_tools_personaContext from "../ai/tools/personaContext.js";
import type * as ai_tools_proactive from "../ai/tools/proactive.js";
import type * as ai_tools_scheduling__context from "../ai/tools/scheduling/_context.js";
import type * as ai_tools_scheduling_index from "../ai/tools/scheduling/index.js";
import type * as ai_tools_scheduling_updateReminder from "../ai/tools/scheduling/updateReminder.js";
import type * as ai_tools_search from "../ai/tools/search.js";
import type * as ai_tools_timeline__context from "../ai/tools/timeline/_context.js";
import type * as ai_tools_timeline_index from "../ai/tools/timeline/index.js";
import type * as ai_tools_timeline_listOrgTimeline from "../ai/tools/timeline/listOrgTimeline.js";
import type * as ai_tools_updateEntity from "../ai/tools/updateEntity.js";
import type * as ai_tools_webSearch from "../ai/tools/webSearch.js";
import type * as ai_webSearchAction from "../ai/webSearchAction.js";
import type * as auth from "../auth.js";
import type * as billing_actions from "../billing/actions.js";
import type * as billing_internal from "../billing/internal.js";
import type * as billing_queries from "../billing/queries.js";
import type * as crm_entities_companies_mutations from "../crm/entities/companies/mutations.js";
import type * as crm_entities_companies_queries from "../crm/entities/companies/queries.js";
import type * as crm_entities_contacts_mutations from "../crm/entities/contacts/mutations.js";
import type * as crm_entities_contacts_queries from "../crm/entities/contacts/queries.js";
import type * as crm_entities_deals_mutations from "../crm/entities/deals/mutations.js";
import type * as crm_entities_deals_queries from "../crm/entities/deals/queries.js";
import type * as crm_entities_leads_mutations from "../crm/entities/leads/mutations.js";
import type * as crm_entities_leads_queries from "../crm/entities/leads/queries.js";
import type * as crm_fields_dedup_helpers from "../crm/fields/dedup/helpers.js";
import type * as crm_fields_fieldDefinitions_internal from "../crm/fields/fieldDefinitions/internal.js";
import type * as crm_fields_fieldDefinitions_migrations from "../crm/fields/fieldDefinitions/migrations.js";
import type * as crm_fields_fieldDefinitions_mutations from "../crm/fields/fieldDefinitions/mutations.js";
import type * as crm_fields_fieldDefinitions_queries from "../crm/fields/fieldDefinitions/queries.js";
import type * as crm_fields_fieldValues_mutations from "../crm/fields/fieldValues/mutations.js";
import type * as crm_fields_fieldValues_queries from "../crm/fields/fieldValues/queries.js";
import type * as crm_fields_pipelines_helpers from "../crm/fields/pipelines/helpers.js";
import type * as crm_fields_pipelines_mutations from "../crm/fields/pipelines/mutations.js";
import type * as crm_fields_pipelines_queries from "../crm/fields/pipelines/queries.js";
import type * as crm_fields_templates_definitions_agency_freelance from "../crm/fields/templates/definitions/agency_freelance.js";
import type * as crm_fields_templates_definitions_b2b_saas from "../crm/fields/templates/definitions/b2b_saas.js";
import type * as crm_fields_templates_definitions_dubai_real_estate from "../crm/fields/templates/definitions/dubai_real_estate.js";
import type * as crm_fields_templates_definitions_freelancer from "../crm/fields/templates/definitions/freelancer.js";
import type * as crm_fields_templates_definitions_generic from "../crm/fields/templates/definitions/generic.js";
import type * as crm_fields_templates_definitions_productivity from "../crm/fields/templates/definitions/productivity.js";
import type * as crm_fields_templates_definitions_real_estate from "../crm/fields/templates/definitions/real_estate.js";
import type * as crm_fields_templates_definitions_real_estate_saudi from "../crm/fields/templates/definitions/real_estate_saudi.js";
import type * as crm_fields_templates_definitions_recruiting from "../crm/fields/templates/definitions/recruiting.js";
import type * as crm_fields_templates_mockSeeder from "../crm/fields/templates/mockSeeder.js";
import type * as crm_fields_templates_mutations from "../crm/fields/templates/mutations.js";
import type * as crm_fields_templates_queries from "../crm/fields/templates/queries.js";
import type * as crm_fields_templates_registry from "../crm/fields/templates/registry.js";
import type * as crm_fields_templates_types from "../crm/fields/templates/types.js";
import type * as crm_people_queries from "../crm/people/queries.js";
import type * as crm_shared_calendar_queries from "../crm/shared/calendar/queries.js";
import type * as crm_shared_conversations_internal from "../crm/shared/conversations/internal.js";
import type * as crm_shared_conversations_mutations from "../crm/shared/conversations/mutations.js";
import type * as crm_shared_conversations_queries from "../crm/shared/conversations/queries.js";
import type * as crm_shared_messages_mutations from "../crm/shared/messages/mutations.js";
import type * as crm_shared_messages_queries from "../crm/shared/messages/queries.js";
import type * as crm_shared_noteCategories_internal from "../crm/shared/noteCategories/internal.js";
import type * as crm_shared_noteCategories_mutations from "../crm/shared/noteCategories/mutations.js";
import type * as crm_shared_noteCategories_queries from "../crm/shared/noteCategories/queries.js";
import type * as crm_shared_notes_mutations from "../crm/shared/notes/mutations.js";
import type * as crm_shared_notes_queries from "../crm/shared/notes/queries.js";
import type * as crm_shared_reminders_mutations from "../crm/shared/reminders/mutations.js";
import type * as crm_shared_reminders_queries from "../crm/shared/reminders/queries.js";
import type * as crm_shared_savedViews_mutations from "../crm/shared/savedViews/mutations.js";
import type * as crm_shared_savedViews_queries from "../crm/shared/savedViews/queries.js";
import type * as crm_shared_tags_internal from "../crm/shared/tags/internal.js";
import type * as crm_shared_tags_mutations from "../crm/shared/tags/mutations.js";
import type * as crm_shared_tags_queries from "../crm/shared/tags/queries.js";
import type * as crm_shared_timeline_queries from "../crm/shared/timeline/queries.js";
import type * as crons from "../crons.js";
import type * as featureFlags_queries from "../featureFlags/queries.js";
import type * as files_mutations from "../files/mutations.js";
import type * as files_queries from "../files/queries.js";
import type * as gdpr_actions from "../gdpr/actions.js";
import type * as gdpr_internal from "../gdpr/internal.js";
import type * as http from "../http.js";
import type * as invitations_actions from "../invitations/actions.js";
import type * as invitations_index from "../invitations/index.js";
import type * as invitations_mutations from "../invitations/mutations.js";
import type * as invitations_queries from "../invitations/queries.js";
import type * as notifications_helpers from "../notifications/helpers.js";
import type * as notifications_mutations from "../notifications/mutations.js";
import type * as notifications_queries from "../notifications/queries.js";
import type * as orgRoles_index from "../orgRoles/index.js";
import type * as orgRoles_mutations from "../orgRoles/mutations.js";
import type * as orgRoles_queries from "../orgRoles/queries.js";
import type * as orgs_helpers from "../orgs/helpers.js";
import type * as orgs_mutations from "../orgs/mutations.js";
import type * as orgs_queries from "../orgs/queries.js";
import type * as orgs_templates_fields from "../orgs/templates/fields.js";
import type * as orgs_templates_pipelineStages from "../orgs/templates/pipelineStages.js";
import type * as schema_ai from "../schema/ai.js";
import type * as schema_crmEntities from "../schema/crmEntities.js";
import type * as schema_crmFields from "../schema/crmFields.js";
import type * as schema_crmShared from "../schema/crmShared.js";
import type * as schema_identity from "../schema/identity.js";
import type * as schema_platform from "../schema/platform.js";
import type * as schema_system from "../schema/system.js";
import type * as trash_mutations from "../trash/mutations.js";
import type * as trash_queries from "../trash/queries.js";
import type * as users_helpers from "../users/helpers.js";
import type * as users_mutations from "../users/mutations.js";
import type * as users_queries from "../users/queries.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  ResendOTPPasswordReset: typeof ResendOTPPasswordReset;
  "_functions/admin": typeof _functions_admin;
  "_functions/authenticated": typeof _functions_authenticated;
  "_migrations/2026_05_21_invitationRoleToRoleId": typeof _migrations_2026_05_21_invitationRoleToRoleId;
  "_migrations/2026_05_22_addOrgSettingsDashboardAndTrash": typeof _migrations_2026_05_22_addOrgSettingsDashboardAndTrash;
  "_migrations/2026_05_22_renameRealEstateTemplateIds": typeof _migrations_2026_05_22_renameRealEstateTemplateIds;
  "_migrations/2026_05_23_addBriefingScopeAndPayload": typeof _migrations_2026_05_23_addBriefingScopeAndPayload;
  "_migrations/2026_05_23_aiPermissionsBackfill": typeof _migrations_2026_05_23_aiPermissionsBackfill;
  "_migrations/2026_05_23_backfillAiThinkingState": typeof _migrations_2026_05_23_backfillAiThinkingState;
  "_migrations/2026_05_23_seedPlatformContext": typeof _migrations_2026_05_23_seedPlatformContext;
  "_migrations/2026_05_23_setSuperAdmin": typeof _migrations_2026_05_23_setSuperAdmin;
  "_migrations/2026_05_23_updateAIPlatformContext": typeof _migrations_2026_05_23_updateAIPlatformContext;
  "_migrations/2026_05_24_addContextBagAndSubagent": typeof _migrations_2026_05_24_addContextBagAndSubagent;
  "_migrations/2026_05_24_dedupeFieldDefinitions": typeof _migrations_2026_05_24_dedupeFieldDefinitions;
  "_migrations/2026_05_24_dropOrgAiContext": typeof _migrations_2026_05_24_dropOrgAiContext;
  "_migrations/2026_05_26_addAiDashboardWidgets": typeof _migrations_2026_05_26_addAiDashboardWidgets;
  "_migrations/2026_05_26_normalizeDashboardMetrics": typeof _migrations_2026_05_26_normalizeDashboardMetrics;
  "_migrations/2026_05_27_addAiMorningBriefingMetric": typeof _migrations_2026_05_27_addAiMorningBriefingMetric;
  "_migrations/2026_05_27_addAiNextActions": typeof _migrations_2026_05_27_addAiNextActions;
  "_migrations/2026_05_28_addAiAnalyticsTables": typeof _migrations_2026_05_28_addAiAnalyticsTables;
  "_migrations/2026_05_28_addPipelineVelocityWidget": typeof _migrations_2026_05_28_addPipelineVelocityWidget;
  "_migrations/2026_05_28_addStandingOrderFirstFireAt": typeof _migrations_2026_05_28_addStandingOrderFirstFireAt;
  "_migrations/2026_05_28_aiStandingOrders": typeof _migrations_2026_05_28_aiStandingOrders;
  "_migrations/addDefaultStage": typeof _migrations_addDefaultStage;
  "_migrations/addNotesColorAndType": typeof _migrations_addNotesColorAndType;
  "_migrations/allowAudioUploads": typeof _migrations_allowAudioUploads;
  "_migrations/consolidatePersonConversations": typeof _migrations_consolidatePersonConversations;
  "_migrations/fixCompanyAssignedToColumnKey": typeof _migrations_fixCompanyAssignedToColumnKey;
  "_migrations/markOnboardedFromMembership": typeof _migrations_markOnboardedFromMembership;
  "_migrations/pinDealFieldsToDefaultStage": typeof _migrations_pinDealFieldsToDefaultStage;
  "_migrations/recomputeOrgStats": typeof _migrations_recomputeOrgStats;
  "_migrations/renameRealEstateToDubai": typeof _migrations_renameRealEstateToDubai;
  "_migrations/seedNoteCategories": typeof _migrations_seedNoteCategories;
  "_migrations/seedSortOrder": typeof _migrations_seedSortOrder;
  "_migrations/seedTemplateDefaults": typeof _migrations_seedTemplateDefaults;
  "_migrations/setOrgDefaultCurrency": typeof _migrations_setOrgDefaultCurrency;
  "_migrations/setOrgPlan": typeof _migrations_setOrgPlan;
  "_migrations/tightenReminderSourceAndAddPriority": typeof _migrations_tightenReminderSourceAndAddPriority;
  "_platform/limits": typeof _platform_limits;
  "_shared/aiApprovals": typeof _shared_aiApprovals;
  "_shared/aiEntityPatch": typeof _shared_aiEntityPatch;
  "_shared/bulkProgress": typeof _shared_bulkProgress;
  "_shared/constants": typeof _shared_constants;
  "_shared/csvEncodingDetect": typeof _shared_csvEncodingDetect;
  "_shared/dedup": typeof _shared_dedup;
  "_shared/enforcePlanLimit": typeof _shared_enforcePlanLimit;
  "_shared/enrichmentErrorMap": typeof _shared_enrichmentErrorMap;
  "_shared/entityCodes": typeof _shared_entityCodes;
  "_shared/errors": typeof _shared_errors;
  "_shared/fieldUpdateLog": typeof _shared_fieldUpdateLog;
  "_shared/notificationKeys": typeof _shared_notificationKeys;
  "_shared/orgStats": typeof _shared_orgStats;
  "_shared/permissions/catalog": typeof _shared_permissions_catalog;
  "_shared/permissions/derive": typeof _shared_permissions_derive;
  "_shared/permissions/helpers": typeof _shared_permissions_helpers;
  "_shared/permissions/index": typeof _shared_permissions_index;
  "_shared/rateLimit": typeof _shared_rateLimit;
  "_shared/recordCodes": typeof _shared_recordCodes;
  "_shared/reservedSlugs": typeof _shared_reservedSlugs;
  "_shared/sanitiseExtractedText": typeof _shared_sanitiseExtractedText;
  "_shared/synonyms": typeof _shared_synonyms;
  "_shared/types": typeof _shared_types;
  "_shared/validators": typeof _shared_validators;
  "_shared/widgetRegistry": typeof _shared_widgetRegistry;
  "_test/helpers": typeof _test_helpers;
  "activityLogs/helpers": typeof activityLogs_helpers;
  "activityLogs/mutations": typeof activityLogs_mutations;
  "ai/_logAIActivityInternal": typeof ai__logAIActivityInternal;
  "ai/actions/analyzeDealClose": typeof ai_actions_analyzeDealClose;
  "ai/actions/analyzeMetric": typeof ai_actions_analyzeMetric;
  "ai/actions/draftMessage": typeof ai_actions_draftMessage;
  "ai/actions/draftProposal": typeof ai_actions_draftProposal;
  "ai/actions/rankNextActions": typeof ai_actions_rankNextActions;
  "ai/actions/rebuildCohorts": typeof ai_actions_rebuildCohorts;
  "ai/actions/summariseConversation": typeof ai_actions_summariseConversation;
  "ai/actions/webScrape": typeof ai_actions_webScrape;
  "ai/aiEntityPatch": typeof ai_aiEntityPatch;
  "ai/analyzeMetricHelpers": typeof ai_analyzeMetricHelpers;
  "ai/availableModels": typeof ai_availableModels;
  "ai/briefings": typeof ai_briefings;
  "ai/briefingsActions": typeof ai_briefingsActions;
  "ai/briefingsPublic": typeof ai_briefingsPublic;
  "ai/chatAttachments": typeof ai_chatAttachments;
  "ai/conversations": typeof ai_conversations;
  "ai/creativeHelpers": typeof ai_creativeHelpers;
  "ai/csvImports": typeof ai_csvImports;
  "ai/dealClose": typeof ai_dealClose;
  "ai/encryption": typeof ai_encryption;
  "ai/encryptionTypes": typeof ai_encryptionTypes;
  "ai/internal": typeof ai_internal;
  "ai/keys": typeof ai_keys;
  "ai/keysActions": typeof ai_keysActions;
  "ai/messages": typeof ai_messages;
  "ai/modelRegistry": typeof ai_modelRegistry;
  "ai/models": typeof ai_models;
  "ai/orchestrator/friendlyToolError": typeof ai_orchestrator_friendlyToolError;
  "ai/orchestrator/modelResolver": typeof ai_orchestrator_modelResolver;
  "ai/orchestrator/orgSchemaContext": typeof ai_orchestrator_orgSchemaContext;
  "ai/orchestrator/quotaGate": typeof ai_orchestrator_quotaGate;
  "ai/orchestrator/reasoningBuffer": typeof ai_orchestrator_reasoningBuffer;
  "ai/orchestrator/resume": typeof ai_orchestrator_resume;
  "ai/orchestrator/router": typeof ai_orchestrator_router;
  "ai/orchestrator/run": typeof ai_orchestrator_run;
  "ai/orchestrator/streamLoop": typeof ai_orchestrator_streamLoop;
  "ai/orchestrator/suggestionGenerator": typeof ai_orchestrator_suggestionGenerator;
  "ai/orchestrator/toolContextBinder": typeof ai_orchestrator_toolContextBinder;
  "ai/orchestrator/twoStepSchemaAudit": typeof ai_orchestrator_twoStepSchemaAudit;
  "ai/orchestrator/zodErrorFormatter": typeof ai_orchestrator_zodErrorFormatter;
  "ai/personaContext": typeof ai_personaContext;
  "ai/processChat": typeof ai_processChat;
  "ai/quarantined/csvParser": typeof ai_quarantined_csvParser;
  "ai/quarantined/csvParserInternal": typeof ai_quarantined_csvParserInternal;
  "ai/quarantined/enrichmentProviders": typeof ai_quarantined_enrichmentProviders;
  "ai/quarantined/enrichmentProvidersInternal": typeof ai_quarantined_enrichmentProvidersInternal;
  "ai/quarantined/fileAnalyzer": typeof ai_quarantined_fileAnalyzer;
  "ai/quarantined/fileAnalyzerInternal": typeof ai_quarantined_fileAnalyzerInternal;
  "ai/queries/anomalies": typeof ai_queries_anomalies;
  "ai/queries/cascadeImpact": typeof ai_queries_cascadeImpact;
  "ai/queries/cohorts": typeof ai_queries_cohorts;
  "ai/queries/insights": typeof ai_queries_insights;
  "ai/queries/memberPerformance": typeof ai_queries_memberPerformance;
  "ai/queries/nextActions": typeof ai_queries_nextActions;
  "ai/queries/pipelineVelocity": typeof ai_queries_pipelineVelocity;
  "ai/queries/telemetry": typeof ai_queries_telemetry;
  "ai/queries/toolTrace": typeof ai_queries_toolTrace;
  "ai/standingOrders/evaluator": typeof ai_standingOrders_evaluator;
  "ai/standingOrders/mutations": typeof ai_standingOrders_mutations;
  "ai/standingOrders/queries": typeof ai_standingOrders_queries;
  "ai/standingOrders/runner": typeof ai_standingOrders_runner;
  "ai/standingOrders/schedule": typeof ai_standingOrders_schedule;
  "ai/standingOrders/triggers": typeof ai_standingOrders_triggers;
  "ai/subagents/crmAction": typeof ai_subagents_crmAction;
  "ai/subagents/csvImport": typeof ai_subagents_csvImport;
  "ai/subagents/enrichment": typeof ai_subagents_enrichment;
  "ai/subagents/index": typeof ai_subagents_index;
  "ai/subagents/qa": typeof ai_subagents_qa;
  "ai/subagents/settings": typeof ai_subagents_settings;
  "ai/subagents/types": typeof ai_subagents_types;
  "ai/suggestions": typeof ai_suggestions;
  "ai/systemPrompt": typeof ai_systemPrompt;
  "ai/telemetry": typeof ai_telemetry;
  "ai/titleGeneration": typeof ai_titleGeneration;
  "ai/toolRegistry": typeof ai_toolRegistry;
  "ai/tools/_shared": typeof ai_tools__shared;
  "ai/tools/analytics/_context": typeof ai_tools_analytics__context;
  "ai/tools/analytics/analyzeMetric": typeof ai_tools_analytics_analyzeMetric;
  "ai/tools/analytics/cohortAnalysis": typeof ai_tools_analytics_cohortAnalysis;
  "ai/tools/analytics/getBriefing": typeof ai_tools_analytics_getBriefing;
  "ai/tools/analytics/index": typeof ai_tools_analytics_index;
  "ai/tools/analytics/memberPerformance": typeof ai_tools_analytics_memberPerformance;
  "ai/tools/analytics/refreshBriefing": typeof ai_tools_analytics_refreshBriefing;
  "ai/tools/companies/_context": typeof ai_tools_companies__context;
  "ai/tools/companies/addPerson": typeof ai_tools_companies_addPerson;
  "ai/tools/companies/index": typeof ai_tools_companies_index;
  "ai/tools/companies/removePerson": typeof ai_tools_companies_removePerson;
  "ai/tools/contextBag": typeof ai_tools_contextBag;
  "ai/tools/creative/_context": typeof ai_tools_creative__context;
  "ai/tools/creative/draftMessage": typeof ai_tools_creative_draftMessage;
  "ai/tools/creative/draftProposal": typeof ai_tools_creative_draftProposal;
  "ai/tools/creative/index": typeof ai_tools_creative_index;
  "ai/tools/creative/summariseConversation": typeof ai_tools_creative_summariseConversation;
  "ai/tools/creative/webScrape": typeof ai_tools_creative_webScrape;
  "ai/tools/crud/_context": typeof ai_tools_crud__context;
  "ai/tools/crud/convertLead": typeof ai_tools_crud_convertLead;
  "ai/tools/crud/createCompany": typeof ai_tools_crud_createCompany;
  "ai/tools/crud/createContact": typeof ai_tools_crud_createContact;
  "ai/tools/crud/createDeal": typeof ai_tools_crud_createDeal;
  "ai/tools/crud/createLead": typeof ai_tools_crud_createLead;
  "ai/tools/crud/deleteEntity": typeof ai_tools_crud_deleteEntity;
  "ai/tools/crud/index": typeof ai_tools_crud_index;
  "ai/tools/crud/revertContact": typeof ai_tools_crud_revertContact;
  "ai/tools/files/_context": typeof ai_tools_files__context;
  "ai/tools/files/index": typeof ai_tools_files_index;
  "ai/tools/files/listFiles": typeof ai_tools_files_listFiles;
  "ai/tools/files/removeFile": typeof ai_tools_files_removeFile;
  "ai/tools/files/updateFileTags": typeof ai_tools_files_updateFileTags;
  "ai/tools/interaction/askChoice": typeof ai_tools_interaction_askChoice;
  "ai/tools/interaction/askInput": typeof ai_tools_interaction_askInput;
  "ai/tools/introspect": typeof ai_tools_introspect;
  "ai/tools/layers/_index": typeof ai_tools_layers__index;
  "ai/tools/layers/bulk": typeof ai_tools_layers_bulk;
  "ai/tools/layers/categories": typeof ai_tools_layers_categories;
  "ai/tools/layers/csvImport": typeof ai_tools_layers_csvImport;
  "ai/tools/layers/csvImportInternal": typeof ai_tools_layers_csvImportInternal;
  "ai/tools/layers/data": typeof ai_tools_layers_data;
  "ai/tools/layers/enrichment": typeof ai_tools_layers_enrichment;
  "ai/tools/layers/enrichmentInternal": typeof ai_tools_layers_enrichmentInternal;
  "ai/tools/layers/fields": typeof ai_tools_layers_fields;
  "ai/tools/layers/fileAnalysis": typeof ai_tools_layers_fileAnalysis;
  "ai/tools/layers/members": typeof ai_tools_layers_members;
  "ai/tools/layers/pipelines": typeof ai_tools_layers_pipelines;
  "ai/tools/layers/settings": typeof ai_tools_layers_settings;
  "ai/tools/layers/tags": typeof ai_tools_layers_tags;
  "ai/tools/layers/templates": typeof ai_tools_layers_templates;
  "ai/tools/layers/views": typeof ai_tools_layers_views;
  "ai/tools/messaging/_context": typeof ai_tools_messaging__context;
  "ai/tools/messaging/addParticipants": typeof ai_tools_messaging_addParticipants;
  "ai/tools/messaging/index": typeof ai_tools_messaging_index;
  "ai/tools/messaging/listMessages": typeof ai_tools_messaging_listMessages;
  "ai/tools/messaging/markThreadRead": typeof ai_tools_messaging_markThreadRead;
  "ai/tools/messaging/removeParticipant": typeof ai_tools_messaging_removeParticipant;
  "ai/tools/messaging/sendMessage": typeof ai_tools_messaging_sendMessage;
  "ai/tools/notes/_context": typeof ai_tools_notes__context;
  "ai/tools/notes/deleteNote": typeof ai_tools_notes_deleteNote;
  "ai/tools/notes/index": typeof ai_tools_notes_index;
  "ai/tools/notes/pinNote": typeof ai_tools_notes_pinNote;
  "ai/tools/notes/setNoteCategory": typeof ai_tools_notes_setNoteCategory;
  "ai/tools/notes/updateNote": typeof ai_tools_notes_updateNote;
  "ai/tools/notesReminders": typeof ai_tools_notesReminders;
  "ai/tools/notifications/_context": typeof ai_tools_notifications__context;
  "ai/tools/notifications/index": typeof ai_tools_notifications_index;
  "ai/tools/notifications/listNotifications": typeof ai_tools_notifications_listNotifications;
  "ai/tools/notifications/markNotificationRead": typeof ai_tools_notifications_markNotificationRead;
  "ai/tools/personaContext": typeof ai_tools_personaContext;
  "ai/tools/proactive": typeof ai_tools_proactive;
  "ai/tools/scheduling/_context": typeof ai_tools_scheduling__context;
  "ai/tools/scheduling/index": typeof ai_tools_scheduling_index;
  "ai/tools/scheduling/updateReminder": typeof ai_tools_scheduling_updateReminder;
  "ai/tools/search": typeof ai_tools_search;
  "ai/tools/timeline/_context": typeof ai_tools_timeline__context;
  "ai/tools/timeline/index": typeof ai_tools_timeline_index;
  "ai/tools/timeline/listOrgTimeline": typeof ai_tools_timeline_listOrgTimeline;
  "ai/tools/updateEntity": typeof ai_tools_updateEntity;
  "ai/tools/webSearch": typeof ai_tools_webSearch;
  "ai/webSearchAction": typeof ai_webSearchAction;
  auth: typeof auth;
  "billing/actions": typeof billing_actions;
  "billing/internal": typeof billing_internal;
  "billing/queries": typeof billing_queries;
  "crm/entities/companies/mutations": typeof crm_entities_companies_mutations;
  "crm/entities/companies/queries": typeof crm_entities_companies_queries;
  "crm/entities/contacts/mutations": typeof crm_entities_contacts_mutations;
  "crm/entities/contacts/queries": typeof crm_entities_contacts_queries;
  "crm/entities/deals/mutations": typeof crm_entities_deals_mutations;
  "crm/entities/deals/queries": typeof crm_entities_deals_queries;
  "crm/entities/leads/mutations": typeof crm_entities_leads_mutations;
  "crm/entities/leads/queries": typeof crm_entities_leads_queries;
  "crm/fields/dedup/helpers": typeof crm_fields_dedup_helpers;
  "crm/fields/fieldDefinitions/internal": typeof crm_fields_fieldDefinitions_internal;
  "crm/fields/fieldDefinitions/migrations": typeof crm_fields_fieldDefinitions_migrations;
  "crm/fields/fieldDefinitions/mutations": typeof crm_fields_fieldDefinitions_mutations;
  "crm/fields/fieldDefinitions/queries": typeof crm_fields_fieldDefinitions_queries;
  "crm/fields/fieldValues/mutations": typeof crm_fields_fieldValues_mutations;
  "crm/fields/fieldValues/queries": typeof crm_fields_fieldValues_queries;
  "crm/fields/pipelines/helpers": typeof crm_fields_pipelines_helpers;
  "crm/fields/pipelines/mutations": typeof crm_fields_pipelines_mutations;
  "crm/fields/pipelines/queries": typeof crm_fields_pipelines_queries;
  "crm/fields/templates/definitions/agency_freelance": typeof crm_fields_templates_definitions_agency_freelance;
  "crm/fields/templates/definitions/b2b_saas": typeof crm_fields_templates_definitions_b2b_saas;
  "crm/fields/templates/definitions/dubai_real_estate": typeof crm_fields_templates_definitions_dubai_real_estate;
  "crm/fields/templates/definitions/freelancer": typeof crm_fields_templates_definitions_freelancer;
  "crm/fields/templates/definitions/generic": typeof crm_fields_templates_definitions_generic;
  "crm/fields/templates/definitions/productivity": typeof crm_fields_templates_definitions_productivity;
  "crm/fields/templates/definitions/real_estate": typeof crm_fields_templates_definitions_real_estate;
  "crm/fields/templates/definitions/real_estate_saudi": typeof crm_fields_templates_definitions_real_estate_saudi;
  "crm/fields/templates/definitions/recruiting": typeof crm_fields_templates_definitions_recruiting;
  "crm/fields/templates/mockSeeder": typeof crm_fields_templates_mockSeeder;
  "crm/fields/templates/mutations": typeof crm_fields_templates_mutations;
  "crm/fields/templates/queries": typeof crm_fields_templates_queries;
  "crm/fields/templates/registry": typeof crm_fields_templates_registry;
  "crm/fields/templates/types": typeof crm_fields_templates_types;
  "crm/people/queries": typeof crm_people_queries;
  "crm/shared/calendar/queries": typeof crm_shared_calendar_queries;
  "crm/shared/conversations/internal": typeof crm_shared_conversations_internal;
  "crm/shared/conversations/mutations": typeof crm_shared_conversations_mutations;
  "crm/shared/conversations/queries": typeof crm_shared_conversations_queries;
  "crm/shared/messages/mutations": typeof crm_shared_messages_mutations;
  "crm/shared/messages/queries": typeof crm_shared_messages_queries;
  "crm/shared/noteCategories/internal": typeof crm_shared_noteCategories_internal;
  "crm/shared/noteCategories/mutations": typeof crm_shared_noteCategories_mutations;
  "crm/shared/noteCategories/queries": typeof crm_shared_noteCategories_queries;
  "crm/shared/notes/mutations": typeof crm_shared_notes_mutations;
  "crm/shared/notes/queries": typeof crm_shared_notes_queries;
  "crm/shared/reminders/mutations": typeof crm_shared_reminders_mutations;
  "crm/shared/reminders/queries": typeof crm_shared_reminders_queries;
  "crm/shared/savedViews/mutations": typeof crm_shared_savedViews_mutations;
  "crm/shared/savedViews/queries": typeof crm_shared_savedViews_queries;
  "crm/shared/tags/internal": typeof crm_shared_tags_internal;
  "crm/shared/tags/mutations": typeof crm_shared_tags_mutations;
  "crm/shared/tags/queries": typeof crm_shared_tags_queries;
  "crm/shared/timeline/queries": typeof crm_shared_timeline_queries;
  crons: typeof crons;
  "featureFlags/queries": typeof featureFlags_queries;
  "files/mutations": typeof files_mutations;
  "files/queries": typeof files_queries;
  "gdpr/actions": typeof gdpr_actions;
  "gdpr/internal": typeof gdpr_internal;
  http: typeof http;
  "invitations/actions": typeof invitations_actions;
  "invitations/index": typeof invitations_index;
  "invitations/mutations": typeof invitations_mutations;
  "invitations/queries": typeof invitations_queries;
  "notifications/helpers": typeof notifications_helpers;
  "notifications/mutations": typeof notifications_mutations;
  "notifications/queries": typeof notifications_queries;
  "orgRoles/index": typeof orgRoles_index;
  "orgRoles/mutations": typeof orgRoles_mutations;
  "orgRoles/queries": typeof orgRoles_queries;
  "orgs/helpers": typeof orgs_helpers;
  "orgs/mutations": typeof orgs_mutations;
  "orgs/queries": typeof orgs_queries;
  "orgs/templates/fields": typeof orgs_templates_fields;
  "orgs/templates/pipelineStages": typeof orgs_templates_pipelineStages;
  "schema/ai": typeof schema_ai;
  "schema/crmEntities": typeof schema_crmEntities;
  "schema/crmFields": typeof schema_crmFields;
  "schema/crmShared": typeof schema_crmShared;
  "schema/identity": typeof schema_identity;
  "schema/platform": typeof schema_platform;
  "schema/system": typeof schema_system;
  "trash/mutations": typeof trash_mutations;
  "trash/queries": typeof trash_queries;
  "users/helpers": typeof users_helpers;
  "users/mutations": typeof users_mutations;
  "users/queries": typeof users_queries;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
