/**
 * B2B SaaS industry template — full end-to-end.
 *
 * Pipeline: Discovery → Demo → Proposal → Negotiation → Closed Won / Lost.
 *
 * Stage-aware fields express BANT (Budget, Authority, Need, Timeline) so
 * the form for a Discovery deal asks "what are they looking for?" while a
 * Negotiation deal asks "what's the contract term and start date?" — the
 * UI never shows BANT fields on a Closed Won record. MRR / ACV / contract
 * term are pinned across the value-bearing stages.
 *
 * Entity labels stay defaults (Lead / Contact / Deal / Company). Pipeline
 * stages are the universal SaaS sales motion — no industry vocabulary.
 *
 * Custom roles cover the typical SaaS revenue org chart:
 *   - Account Executive (AE) — owns deals through close
 *   - BDR / SDR             — owns leads, qualifies, hands to AE
 *   - Customer Success      — owns post-sale relationship
 */
import type { IndustryTemplate } from "../../../crm/fields/templates/types";

export const b2bSaasTemplate: IndustryTemplate = {
	id: "b2b-saas",
	label: "B2B SaaS",
	description:
		"Universal SaaS sales pipeline — discovery, demo, proposal, close. BANT fields, MRR / ACV tracking, BDR + AE + CSM roles.",
	icon: "💻",
	region: "global",

	// ─── Workspace defaults ───────────────────────────────────────────────
	defaults: {
		currency: "USD",
		timezone: "America/Los_Angeles",
		leadStaleAfterDays: 7,
		locale: "en",
	},

	// ─── Code prefixes (P-001 / D-001 / C-001 / T-001) ────────────────────
	codePrefixes: {
		person: "P",
		deal: "D",
		company: "C",
	},

	// ─── Pipeline ──────────────────────────────────────────────────────────
	pipeline: {
		name: "Sales Pipeline",
		stages: [
			{
				name: "Discovery",
				code: "DISC",
				color: "#6366f1",
				staleAfterDays: 5,
				warningAfterDays: 3,
			},
			{
				name: "Demo Scheduled",
				code: "DEMO",
				color: "#8b5cf6",
				staleAfterDays: 7,
				warningAfterDays: 5,
			},
			{
				name: "Proposal Sent",
				code: "PROP",
				color: "#a855f7",
				staleAfterDays: 7,
				warningAfterDays: 5,
			},
			{
				name: "Negotiation",
				code: "NEG",
				color: "#d946ef",
				staleAfterDays: 10,
				warningAfterDays: 7,
			},
			{
				name: "Closed Won",
				code: "WON",
				color: "#22c55e",
				isFinal: true,
				finalType: "positive",
			},
			{
				name: "Closed Lost",
				code: "LOST",
				color: "#ef4444",
				isFinal: true,
				finalType: "negative",
			},
		],
	},

	// ─── Field definitions ────────────────────────────────────────────────
	fieldDefinitions: {
		lead: [
			{
				entityType: "lead",
				name: "company_size",
				label: "Company Size",
				type: "select",
				kind: "select",
				storage: "fieldValues",
				groupName: "Firmographic",
				options: ["1-10", "11-50", "51-200", "201-1000", "1000-5000", "5000+"],
			},
			{
				entityType: "lead",
				name: "industry_vertical",
				label: "Industry Vertical",
				type: "select",
				kind: "select",
				storage: "fieldValues",
				groupName: "Firmographic",
				options: [
					"SaaS",
					"E-commerce",
					"Fintech",
					"Healthcare",
					"Education",
					"Manufacturing",
					"Logistics",
					"Media",
					"Professional Services",
					"Other",
				],
			},
			{
				entityType: "lead",
				name: "lead_source_detail",
				label: "Source Detail",
				type: "select",
				kind: "select",
				storage: "fieldValues",
				groupName: "Attribution",
				options: [
					"Inbound — website",
					"Inbound — content",
					"Outbound — cold email",
					"Outbound — LinkedIn",
					"Outbound — call",
					"Event / conference",
					"Referral — partner",
					"Referral — customer",
					"Self-serve signup",
				],
			},
		],
		contact: [
			{
				entityType: "contact",
				name: "job_title",
				label: "Job Title",
				type: "text",
				kind: "text",
				storage: "fieldValues",
				groupName: "Personal",
			},
			{
				entityType: "contact",
				name: "seniority",
				label: "Seniority",
				type: "select",
				kind: "select",
				storage: "fieldValues",
				groupName: "Personal",
				options: ["IC", "Manager", "Senior Manager / Director", "VP", "C-Level", "Founder"],
			},
			{
				entityType: "contact",
				name: "is_decision_maker",
				label: "Decision Maker?",
				type: "boolean",
				kind: "boolean",
				storage: "fieldValues",
				groupName: "Sales",
			},
			{
				entityType: "contact",
				name: "linkedin_url",
				label: "LinkedIn",
				type: "url",
				kind: "url",
				storage: "fieldValues",
				groupName: "Personal",
			},
		],
		company: [
			{
				entityType: "company",
				name: "domain",
				label: "Primary Domain",
				type: "url",
				kind: "url",
				storage: "fieldValues",
				groupName: "Firmographic",
			},
			{
				entityType: "company",
				name: "headcount",
				label: "Headcount",
				type: "number",
				kind: "number",
				storage: "fieldValues",
				groupName: "Firmographic",
			},
			{
				entityType: "company",
				name: "tech_stack",
				label: "Tech Stack",
				type: "multiselect",
				kind: "multiselect",
				storage: "fieldValues",
				groupName: "Firmographic",
				options: [
					"AWS",
					"GCP",
					"Azure",
					"Salesforce",
					"HubSpot",
					"Slack",
					"Microsoft Teams",
					"Google Workspace",
					"Office 365",
					"Notion",
					"Linear",
					"Jira",
					"Other",
				],
			},
		],
		deal: [
			// ── Always visible ──────────────────────────────────────────
			{
				entityType: "deal",
				name: "mrr_usd",
				label: "MRR (USD)",
				type: "currency",
				kind: "currency",
				storage: "fieldValues",
				groupName: "Financial",
			},
			{
				entityType: "deal",
				name: "acv_usd",
				label: "ACV (USD)",
				type: "currency",
				kind: "currency",
				storage: "fieldValues",
				groupName: "Financial",
			},
			{
				entityType: "deal",
				name: "product_line",
				label: "Product Line",
				type: "select",
				kind: "select",
				storage: "fieldValues",
				groupName: "Product",
				options: ["Starter", "Pro", "Business", "Enterprise"],
			},
			// ── Discovery + Demo: BANT + Need ──────────────────────────
			{
				entityType: "deal",
				name: "primary_use_case",
				label: "Primary Use Case",
				type: "text",
				kind: "text",
				storage: "fieldValues",
				groupName: "Discovery",
				showInStages: ["DISC", "DEMO", "PROP", "NEG"],
				required: false,
			},
			{
				entityType: "deal",
				name: "current_solution",
				label: "Current Solution",
				type: "text",
				kind: "text",
				storage: "fieldValues",
				groupName: "Discovery",
				showInStages: ["DISC", "DEMO"],
			},
			{
				entityType: "deal",
				name: "evaluation_criteria",
				label: "Evaluation Criteria",
				type: "text",
				kind: "text",
				storage: "fieldValues",
				groupName: "Discovery",
				showInStages: ["DISC", "DEMO", "PROP"],
			},
			// ── Proposal + Negotiation: BANT details ───────────────────
			{
				entityType: "deal",
				name: "budget_band",
				label: "Budget Band",
				type: "select",
				kind: "select",
				storage: "fieldValues",
				groupName: "BANT",
				options: ["< $10K", "$10K – $25K", "$25K – $50K", "$50K – $100K", "$100K+"],
				showInStages: ["DEMO", "PROP", "NEG"],
				required: true,
			},
			{
				entityType: "deal",
				name: "decision_maker",
				label: "Decision Maker",
				type: "text",
				kind: "text",
				storage: "fieldValues",
				groupName: "BANT",
				showInStages: ["DEMO", "PROP", "NEG"],
				required: true,
			},
			{
				entityType: "deal",
				name: "decision_timeline",
				label: "Decision Timeline",
				type: "select",
				kind: "select",
				storage: "fieldValues",
				groupName: "BANT",
				options: [
					"This week",
					"This month",
					"Next quarter",
					"Next half",
					"This year",
					"Unsure",
				],
				showInStages: ["DEMO", "PROP", "NEG"],
				required: true,
			},
			{
				entityType: "deal",
				name: "champion",
				label: "Champion",
				type: "text",
				kind: "text",
				storage: "fieldValues",
				groupName: "BANT",
				showInStages: ["DEMO", "PROP", "NEG"],
			},
			// ── Proposal + Negotiation: Contract details ───────────────
			{
				entityType: "deal",
				name: "contract_term_months",
				label: "Contract Term (months)",
				type: "number",
				kind: "number",
				storage: "fieldValues",
				groupName: "Contract",
				showInStages: ["PROP", "NEG", "WON"],
			},
			{
				entityType: "deal",
				name: "billing_cycle",
				label: "Billing Cycle",
				type: "select",
				kind: "select",
				storage: "fieldValues",
				groupName: "Contract",
				options: ["Monthly", "Quarterly", "Annual", "Multi-year"],
				showInStages: ["PROP", "NEG", "WON"],
			},
			{
				entityType: "deal",
				name: "discount_pct",
				label: "Discount %",
				type: "number",
				kind: "number",
				storage: "fieldValues",
				groupName: "Contract",
				showInStages: ["NEG", "WON"],
			},
			{
				entityType: "deal",
				name: "expected_start_date",
				label: "Expected Start Date",
				type: "date",
				kind: "date",
				storage: "fieldValues",
				groupName: "Contract",
				showInStages: ["NEG", "WON"],
			},
			// ── Lost diagnostics ───────────────────────────────────────
			{
				entityType: "deal",
				name: "lost_reason_category",
				label: "Lost Reason",
				type: "select",
				kind: "select",
				storage: "fieldValues",
				groupName: "Outcome",
				options: [
					"Price",
					"Product gap",
					"Lost to competitor",
					"No decision / stalled",
					"Bad timing",
					"Internal champion left",
					"Budget cut",
					"Other",
				],
				showInStages: ["LOST"],
			},
			{
				entityType: "deal",
				name: "lost_to_competitor",
				label: "Lost to (competitor)",
				type: "text",
				kind: "text",
				storage: "fieldValues",
				groupName: "Outcome",
				showInStages: ["LOST"],
			},
		],
	},

	// ─── Modules slot map (deal pipeline is a board first) ────────────────
	modules: [
		{
			slot: "lead",
			order: 0,
			defaultView: "list",
			cardFields: ["displayName", "company_size", "industry_vertical", "assignedTo"],
			listColumns: [
				"displayName",
				"personCode",
				"email",
				"company_size",
				"industry_vertical",
				"lead_source_detail",
				"assignedTo",
				"status",
			],
			boardGroupBy: "status",
		},
		{
			slot: "contact",
			order: 1,
			defaultView: "list",
			cardFields: ["displayName", "job_title", "seniority", "assignedTo"],
			listColumns: [
				"displayName",
				"personCode",
				"email",
				"job_title",
				"seniority",
				"is_decision_maker",
				"companyId",
				"assignedTo",
			],
			boardGroupBy: "assignedTo",
		},
		{
			slot: "deal",
			order: 2,
			defaultView: "board",
			cardFields: ["title", "acv_usd", "decision_timeline", "assignedTo"],
			listColumns: [
				"dealCode",
				"title",
				"companyId",
				"acv_usd",
				"mrr_usd",
				"product_line",
				"currentStageId",
				"assignedTo",
				"expectedCloseDate",
			],
			boardGroupBy: "currentStageId",
		},
		{
			slot: "company",
			order: 3,
			defaultView: "list",
			cardFields: ["name", "headcount", "industry"],
			listColumns: ["name", "companyCode", "domain", "industry", "headcount", "assignedTo"],
			boardGroupBy: "industry",
		},
	],

	// ─── Sticky-note categories (sales workflow, standardized) ───────────
	noteCategories: [
		{ name: "Urgent", bgColor: "#fecaca", isDefault: false, position: 0 },
		{ name: "Today", bgColor: "#fde68a", isDefault: true, position: 1 },
		{ name: "Discovery", bgColor: "#bae6fd", isDefault: false, position: 2 },
		{ name: "Demo Prep", bgColor: "#ddd6fe", isDefault: false, position: 3 },
		{ name: "Done", bgColor: "#a7f3d0", isDefault: false, position: 4 },
	],

	// ─── Tag presets ──────────────────────────────────────────────────────
	tags: [
		{ name: "Champion", color: "#22c55e" },
		{ name: "Decision maker", color: "#3b82f6" },
		{ name: "Influencer", color: "#a855f7" },
		{ name: "Blocker", color: "#ef4444" },
		{ name: "ICP fit", color: "#10b981" },
		{ name: "Out of ICP", color: "#94a3b8" },
		{ name: "Stalled", color: "#f59e0b" },
		{ name: "Renewal", color: "#06b6d4" },
		{ name: "Expansion", color: "#84cc16" },
		{ name: "Win-back", color: "#ec4899" },
		{ name: "Inbound", color: "#6366f1" },
		{ name: "Outbound", color: "#d946ef" },
	],

	// ─── Reminder defaults ────────────────────────────────────────────────
	briefingDefaults: {
		morningBriefingEnabled: true,
		morningBriefingTime: "09:00",
	},

	// ─── Follow-up cadence defaults ───────────────────────────────────────
	taskDefaults: {
		defaultDueOffsetDays: 3,
		defaultPriority: "normal",
		notifyAssignee: true,
		requireDealCode: false,
		reminderBeforeHours: 1,
	},

	// ─── File-upload policy (proposals + contracts) ───────────────────────
	fileUpload: {
		allowedMimeCategories: ["pdf", "document", "spreadsheet", "image"],
		maxSizeMb: 30,
	},

	// ─── AI persona ───────────────────────────────────────────────────────
	aiPersona:
		"You are a B2B SaaS sales coach embedded in the user's CRM. Speak the language of MEDDPICC / BANT / SPICED — Champion, Economic Buyer, Decision Criteria, Decision Process, Identify Pain, Competition, Budget, Authority, Need, Timeline. Pipeline stages: Discovery → Demo Scheduled → Proposal Sent → Negotiation → Closed Won / Closed Lost. Push the rep to qualify hard at Discovery (uncover pain + champion), confirm BANT before sending a proposal, and document the lost reason on every Closed Lost. When the rep asks for forecast advice, weight by stage probability and remind them about deals that have been stale longer than the stage's staleAfterDays. Use the org's default currency for all values. Always confirm before destructive actions (Closed Lost on a high-ACV deal, mass updates).",

	// ─── Dashboard widgets (ranked) ────────────────────────────────────────
	dashboardMetrics: [
		"ai.morningBriefing",
		"ai.pulseRibbon",
		"ai.quickComposer",
		"deals.open",
		"deals.pipelineValue",
		"deals.won",
		"deals.lost",
		"deals.pipeline",
		"tasks.list",
		"today.focus",
		"messages.recent",
		"activity.recent",
		"calendar.weekAhead",
		"pipeline.velocity",
	],

	// ─── Custom orgRoles ──────────────────────────────────────────────────
	customRoles: [
		{
			name: "Account Executive",
			description: "Owns deals from qualification through close.",
			color: "#3b82f6",
			permissions: [
				"leads.view",
				"leads.update",
				"leads.qualify",
				"leads.convert",
				"contacts.view",
				"contacts.create",
				"contacts.update",
				"companies.view",
				"companies.update",
				"deals.view",
				"deals.create",
				"deals.update",
				"deals.changeStage",
				"deals.viewValues",
				"deals.close",
				"notes.view",
				"notes.create",
				"notes.updateOwn",
				"notes.deleteOwn",
				"messages.view",
				"messages.send",
				"messages.editOwn",
				"messages.deleteOwn",
				"messages.subscribe",
				"tasks.view",
				"tasks.create",
				"tasks.manage",
				"tags.view",
				"tags.attach",
				"savedViews.view",
				"savedViews.createPersonal",
				"pipelines.view",
				"fieldDefinitions.view",
				"ai.use",
				"ai.viewHistory",
				"activityLogs.viewOwn",
				"notifications.viewOwn",
				"notifications.markRead",
				"files.view",
				"files.upload",
				"files.delete",
			],
		},
		{
			name: "BDR",
			description: "Top-of-funnel — works leads, books meetings, hands to AE.",
			color: "#a855f7",
			permissions: [
				"leads.view",
				"leads.create",
				"leads.update",
				"leads.qualify",
				"contacts.view",
				"contacts.create",
				"contacts.update",
				"companies.view",
				"companies.create",
				"deals.view",
				"deals.viewValues",
				"notes.view",
				"notes.create",
				"notes.updateOwn",
				"notes.deleteOwn",
				"messages.view",
				"messages.send",
				"messages.editOwn",
				"messages.deleteOwn",
				"messages.subscribe",
				"tasks.view",
				"tasks.create",
				"tasks.manage",
				"tags.view",
				"tags.attach",
				"savedViews.view",
				"savedViews.createPersonal",
				"pipelines.view",
				"fieldDefinitions.view",
				"ai.use",
				"ai.viewHistory",
				"activityLogs.viewOwn",
				"notifications.viewOwn",
				"notifications.markRead",
				"files.view",
				"files.upload",
				"files.delete",
			],
		},
		{
			name: "Customer Success",
			description: "Owns post-sale — onboarding, renewals, expansion.",
			color: "#10b981",
			permissions: [
				"contacts.view",
				"contacts.update",
				"companies.view",
				"companies.update",
				"deals.view",
				"deals.viewValues",
				"deals.update",
				"notes.view",
				"notes.create",
				"notes.updateOwn",
				"notes.deleteOwn",
				"messages.view",
				"messages.send",
				"messages.editOwn",
				"messages.deleteOwn",
				"messages.subscribe",
				"tasks.view",
				"tasks.create",
				"tasks.manage",
				"tags.view",
				"tags.attach",
				"savedViews.view",
				"savedViews.createPersonal",
				"pipelines.view",
				"fieldDefinitions.view",
				"ai.use",
				"ai.viewHistory",
				"activityLogs.viewOwn",
				"notifications.viewOwn",
				"notifications.markRead",
				"files.view",
				"files.upload",
				"files.delete",
			],
		},
	],

	// ─── Saved views (sidebar shortcuts) ──────────────────────────────────
	savedViews: [
		{
			entityType: "deal",
			name: "Closing this month",
			scope: "org",
			isPinned: true,
			filters: JSON.stringify({ closeWithin: "30d", excludeFinal: true }),
			sortBy: "expectedCloseDate",
			sortOrder: "asc",
		},
		{
			entityType: "deal",
			name: "Stalled deals (>14d)",
			scope: "org",
			isPinned: true,
			filters: JSON.stringify({ staleAfterDays: 14, excludeFinal: true }),
			sortBy: "updatedAt",
			sortOrder: "asc",
		},
		{
			entityType: "deal",
			name: "Demos this week",
			scope: "org",
			isPinned: true,
			filters: JSON.stringify({ stage: "DEMO", scheduledWithin: "7d" }),
			sortBy: "expectedCloseDate",
			sortOrder: "asc",
		},
		{
			entityType: "deal",
			name: "My open deals",
			scope: "user",
			isPinned: true,
			filters: JSON.stringify({ assignedToMe: true, excludeFinal: true }),
			sortBy: "updatedAt",
			sortOrder: "desc",
		},
		{
			entityType: "deal",
			name: "Lost — win-back candidates",
			scope: "org",
			isPinned: false,
			filters: JSON.stringify({
				stage: "LOST",
				lostReasonNot: "Bad timing",
				lostWithin: "180d",
			}),
			sortBy: "lostAt",
			sortOrder: "desc",
		},
		{
			entityType: "lead",
			name: "Hot inbound (mine)",
			scope: "user",
			isPinned: true,
			filters: JSON.stringify({
				assignedToMe: true,
				status: "new",
				sourceContains: "Inbound",
			}),
			sortBy: "createdAt",
			sortOrder: "desc",
		},
		{
			entityType: "lead",
			name: "Stale leads (>7d)",
			scope: "org",
			isPinned: false,
			filters: JSON.stringify({ staleAfterDays: 7, statusNot: "converted" }),
			sortBy: "updatedAt",
			sortOrder: "asc",
		},
	],

	// ─── Mock data (Phase 3A — deletable sample records) ──────────────────
	mockData: {
		companies: [
			{
				key: "acme-corp",
				name: "Acme Corp",
				industry: "SaaS",
				website: "https://acme.example.com",
				fieldValues: {
					domain: "acme.example.com",
					headcount: 120,
				},
			},
		],
		leads: [
			{
				displayName: "Julia Rodriguez",
				email: "julia.r@acme.example.com",
				phone: "+1 415 555 0201",
				status: "new",
				fieldValues: {
					company_size: "51-200",
					industry_vertical: "SaaS",
					lead_source_detail: "Inbound — website",
				},
				tags: ["ICP fit", "Inbound"],
			},
			{
				displayName: "Marcus Lee",
				email: "marcus@buildplex.example.com",
				phone: "+1 213 555 0202",
				status: "contacted",
				fieldValues: {
					company_size: "201-1000",
					industry_vertical: "Logistics",
					lead_source_detail: "Outbound — LinkedIn",
				},
				tags: ["Champion"],
			},
			{
				displayName: "Fatima Al-Hassan",
				email: "fatima.h@novatech.example.com",
				phone: "+44 20 7946 0203",
				status: "new",
				fieldValues: {
					company_size: "11-50",
					industry_vertical: "Fintech",
					lead_source_detail: "Event / conference",
				},
				tags: ["ICP fit", "Decision maker"],
			},
		],
		contacts: [
			{
				displayName: "Daniel Kim",
				email: "daniel.k@acme.example.com",
				companyKey: "acme-corp",
				fieldValues: {
					job_title: "VP Engineering",
					seniority: "VP",
					is_decision_maker: true,
					linkedin_url: "https://linkedin.com/in/daniel-kim-example",
				},
				tags: ["Champion", "Decision maker"],
			},
			{
				displayName: "Sarah Chen",
				email: "sarah.c@acme.example.com",
				companyKey: "acme-corp",
				fieldValues: {
					job_title: "Senior Engineering Manager",
					seniority: "Senior Manager / Director",
					is_decision_maker: false,
				},
				tags: ["Influencer"],
			},
		],
		deals: [
			{
				title: "Acme Corp — Pro plan, 50 seats",
				stageCode: "DISC",
				value: 60000,
				contactDisplayName: "Daniel Kim",
				companyKey: "acme-corp",
				fieldValues: {
					mrr_usd: 5000,
					acv_usd: 60000,
					product_line: "Pro",
					primary_use_case: "Internal CRM consolidation across BD + AE teams",
					evaluation_criteria: "Stage-aware fields + AI assistant + India compliance",
				},
				tags: ["ICP fit", "Inbound"],
			},
			{
				title: "Buildplex — Enterprise rollout",
				stageCode: "PROP",
				value: 240000,
				fieldValues: {
					mrr_usd: 20000,
					acv_usd: 240000,
					product_line: "Enterprise",
					budget_band: "$100K+",
					decision_maker: "Marcus Lee (VP Operations)",
					decision_timeline: "Next quarter",
					champion: "Marcus Lee",
					contract_term_months: 12,
					billing_cycle: "Annual",
				},
				tags: ["Champion", "ICP fit"],
			},
		],
		notes: [
			{
				content:
					"Discovery call done — Daniel confirmed BANT. Acme uses HubSpot today, frustrated with stage-field mapping. Strong fit.",
				categoryName: "Discovery",
				anchorTo: { kind: "deal", title: "Acme Corp — Pro plan, 50 seats" },
			},
			{
				content:
					"Demo scheduled Thursday 2pm PT for Acme. Prep: industry-template flow + AI assistant teaser.",
				categoryName: "Demo Prep",
				anchorTo: { kind: "deal", title: "Acme Corp — Pro plan, 50 seats" },
			},
			{
				content:
					"Buildplex sent revised proposal — they want 12-month term + 15% discount. Need to confirm with sales leadership.",
				categoryName: "Urgent",
				anchorTo: { kind: "deal", title: "Buildplex — Enterprise rollout" },
			},
			{
				content:
					"Fatima at NovaTech mentioned competitor X — research how we differentiate.",
				categoryName: "Today",
				anchorTo: { kind: "lead", displayName: "Fatima Al-Hassan" },
			},
		],
		tasks: [
			{
				title: "Acme demo prep — finalize deck",
				dueOffsetDays: 0,
				priority: "high",
				source: "manual",
				anchorTo: { kind: "deal", title: "Acme Corp — Pro plan, 50 seats" },
			},
			{
				title: "Send Buildplex revised proposal",
				dueOffsetDays: 1,
				priority: "urgent",
				source: "followup",
				anchorTo: { kind: "deal", title: "Buildplex — Enterprise rollout" },
			},
			{
				title: "Discovery call — Fatima at NovaTech",
				dueOffsetDays: 2,
				priority: "high",
				source: "manual",
				anchorTo: { kind: "lead", displayName: "Fatima Al-Hassan" },
			},
		],
	},
};
