/**
 * Recruiting / Staffing industry template — full end-to-end.
 *
 * Pipeline: Sourced → Screened → Phone Interview → Onsite → Offer →
 *           Hired | Rejected.
 *
 * Entity renames:
 *   Lead    → Candidate
 *   Contact → Hiring Manager
 *   Deal    → Placement
 *   Company → Client Company
 *
 * Sensitive fields: resume, salary expectation, current salary — all marked
 * `sensitive: true` so they're excluded from AI prompts for non-admin roles.
 */
import type { IndustryTemplate } from "../../../crm/fields/templates/types";
import { recruitingMockData } from "../mockData/recruiting";

export const recruitingTemplate: IndustryTemplate = {
	id: "recruiting",
	label: "Recruiting / Staffing",
	description:
		"Candidate pipeline — source, screen, interview, offer, hire. Resume + salary tracking with privacy controls.",
	icon: "👥",
	region: "global",

	defaults: {
		currency: "USD",
		timezone: "UTC",
		leadStaleAfterDays: 10,
		locale: "en",
	},

	entityLabels: {
		lead: { singular: "Candidate", plural: "Candidates", slug: "candidates" },
		contact: { singular: "Hiring Manager", plural: "Hiring Managers", slug: "hiring-managers" },
		deal: { singular: "Placement", plural: "Placements", slug: "placements" },
		company: {
			singular: "Client Company",
			plural: "Client Companies",
			slug: "client-companies",
		},
	},

	codePrefixes: { person: "CAN", deal: "PL", company: "CC" },

	pipeline: {
		name: "Recruitment Pipeline",
		stages: [
			{ name: "Sourced", code: "SRC", color: "#6366f1", staleAfterDays: 5 },
			{ name: "Screened", code: "SCR", color: "#8b5cf6", staleAfterDays: 3 },
			{ name: "Phone Interview", code: "PHN", color: "#a855f7", staleAfterDays: 5 },
			{ name: "Onsite / Technical", code: "ONS", color: "#f59e0b", staleAfterDays: 7 },
			{ name: "Offer Extended", code: "OFR", color: "#3b82f6", staleAfterDays: 5 },
			{
				name: "Hired",
				code: "HIRED",
				color: "#22c55e",
				isFinal: true,
				finalType: "positive",
			},
			{
				name: "Rejected",
				code: "REJ",
				color: "#ef4444",
				isFinal: true,
				finalType: "negative",
			},
			{
				name: "Withdrawn",
				code: "WDN",
				color: "#94a3b8",
				isFinal: true,
				finalType: "neutral",
			},
		],
	},

	fieldDefinitions: {
		lead: [
			{
				entityType: "lead",
				name: "skills",
				label: "Skills",
				type: "multiselect",
				kind: "multiselect",
				storage: "fieldValues",
				groupName: "Profile",
				options: [
					"JavaScript",
					"TypeScript",
					"React",
					"Node.js",
					"Python",
					"Java",
					"Go",
					"Rust",
					"AWS",
					"DevOps",
					"Design",
					"Product",
					"Marketing",
					"Sales",
					"Finance",
					"HR",
					"Other",
				],
			},
			{
				entityType: "lead",
				name: "years_experience",
				label: "Years of Experience",
				type: "number",
				kind: "number",
				storage: "fieldValues",
				groupName: "Profile",
			},
			{
				entityType: "lead",
				name: "current_title",
				label: "Current Title",
				type: "text",
				kind: "text",
				storage: "fieldValues",
				groupName: "Profile",
			},
			{
				entityType: "lead",
				name: "current_company",
				label: "Current Company",
				type: "text",
				kind: "text",
				storage: "fieldValues",
				groupName: "Profile",
			},
			{
				entityType: "lead",
				name: "location",
				label: "Location",
				type: "text",
				kind: "text",
				storage: "fieldValues",
				groupName: "Profile",
			},
			{
				entityType: "lead",
				name: "linkedin_url",
				label: "LinkedIn",
				type: "url",
				kind: "url",
				storage: "fieldValues",
				groupName: "Profile",
			},
			{
				entityType: "lead",
				name: "resume_file",
				label: "Resume / CV",
				type: "file",
				kind: "file",
				storage: "fieldValues",
				groupName: "Documents",
				sensitive: true,
			},
			{
				entityType: "lead",
				name: "salary_expectation",
				label: "Salary Expectation",
				type: "currency",
				kind: "currency",
				storage: "fieldValues",
				groupName: "Compensation",
				sensitive: true,
			},
			{
				entityType: "lead",
				name: "current_salary",
				label: "Current Salary",
				type: "currency",
				kind: "currency",
				storage: "fieldValues",
				groupName: "Compensation",
				sensitive: true,
			},
			{
				entityType: "lead",
				name: "notice_period",
				label: "Notice Period",
				type: "select",
				kind: "select",
				storage: "fieldValues",
				groupName: "Availability",
				options: ["Immediate", "2 weeks", "1 month", "2 months", "3 months"],
			},
			{
				entityType: "lead",
				name: "work_authorization",
				label: "Work Authorization",
				type: "select",
				kind: "select",
				storage: "fieldValues",
				groupName: "Availability",
				options: ["Citizen", "Permanent Resident", "Work Visa", "Needs Sponsorship"],
			},
		],
		contact: [
			{
				entityType: "contact",
				name: "department",
				label: "Department",
				type: "text",
				kind: "text",
				storage: "fieldValues",
				groupName: "Role",
			},
			{
				entityType: "contact",
				name: "hiring_urgency",
				label: "Hiring Urgency",
				type: "select",
				kind: "select",
				storage: "fieldValues",
				groupName: "Role",
				options: ["Backfill (urgent)", "Growth (normal)", "Future pipeline", "Exploratory"],
			},
		],
		company: [
			{
				entityType: "company",
				name: "headcount",
				label: "Headcount",
				type: "number",
				kind: "number",
				storage: "fieldValues",
				groupName: "Firmographic",
			},
			{
				entityType: "company",
				name: "open_roles_count",
				label: "Open Roles",
				type: "number",
				kind: "number",
				storage: "fieldValues",
				groupName: "Engagement",
			},
			{
				entityType: "company",
				name: "fee_structure",
				label: "Fee Structure",
				type: "select",
				kind: "select",
				storage: "fieldValues",
				groupName: "Commercial",
				options: [
					"Contingency 15%",
					"Contingency 20%",
					"Contingency 25%",
					"Retained",
					"RPO",
					"Flat fee",
				],
			},
		],
		deal: [
			{
				entityType: "deal",
				name: "role_title",
				label: "Role Title",
				type: "text",
				kind: "text",
				storage: "fieldValues",
				groupName: "Position",
				required: true,
			},
			{
				entityType: "deal",
				name: "role_level",
				label: "Level",
				type: "select",
				kind: "select",
				storage: "fieldValues",
				groupName: "Position",
				options: [
					"Junior",
					"Mid",
					"Senior",
					"Staff",
					"Principal",
					"Director",
					"VP",
					"C-Level",
				],
			},
			{
				entityType: "deal",
				name: "comp_band_min",
				label: "Comp Band Min",
				type: "currency",
				kind: "currency",
				storage: "fieldValues",
				groupName: "Compensation",
				sensitive: true,
			},
			{
				entityType: "deal",
				name: "comp_band_max",
				label: "Comp Band Max",
				type: "currency",
				kind: "currency",
				storage: "fieldValues",
				groupName: "Compensation",
				sensitive: true,
			},
			{
				entityType: "deal",
				name: "placement_fee",
				label: "Placement Fee",
				type: "currency",
				kind: "currency",
				storage: "fieldValues",
				groupName: "Commercial",
				showInStages: ["OFR", "HIRED"],
			},
			{
				entityType: "deal",
				name: "start_date",
				label: "Start Date",
				type: "date",
				kind: "date",
				storage: "fieldValues",
				groupName: "Position",
				showInStages: ["OFR", "HIRED"],
			},
			{
				entityType: "deal",
				name: "offer_amount",
				label: "Offer Amount",
				type: "currency",
				kind: "currency",
				storage: "fieldValues",
				groupName: "Compensation",
				sensitive: true,
				showInStages: ["OFR", "HIRED"],
			},
			{
				entityType: "deal",
				name: "rejection_reason",
				label: "Rejection Reason",
				type: "select",
				kind: "select",
				storage: "fieldValues",
				groupName: "Outcome",
				options: [
					"Culture fit",
					"Technical skills",
					"Overqualified",
					"Underqualified",
					"Salary mismatch",
					"Candidate withdrew",
					"Position filled",
					"Hiring freeze",
					"Other",
				],
				showInStages: ["REJ", "WDN"],
			},
			{
				entityType: "deal",
				name: "interview_feedback",
				label: "Interview Feedback",
				type: "text",
				kind: "text",
				storage: "fieldValues",
				groupName: "Assessment",
				showInStages: ["PHN", "ONS", "OFR", "HIRED", "REJ"],
			},
		],
	},

	modules: [
		{
			slot: "lead",
			order: 0,
			defaultView: "board",
			cardFields: ["displayName", "current_title", "skills", "years_experience"],
			listColumns: [
				"displayName",
				"personCode",
				"current_title",
				"current_company",
				"skills",
				"years_experience",
				"salary_expectation",
				"notice_period",
				"assignedTo",
				"status",
			],
			boardGroupBy: "status",
		},
		{
			slot: "contact",
			order: 1,
			defaultView: "board",
			cardFields: ["displayName", "department", "hiring_urgency"],
			listColumns: [
				"displayName",
				"personCode",
				"email",
				"department",
				"hiring_urgency",
				"companyId",
				"assignedTo",
			],
			boardGroupBy: "assignedTo",
		},
		{
			slot: "deal",
			order: 2,
			defaultView: "board",
			cardFields: ["title", "role_title", "role_level", "comp_band_max", "assignedTo"],
			listColumns: [
				"dealCode",
				"title",
				"role_title",
				"role_level",
				"comp_band_min",
				"comp_band_max",
				"currentStageId",
				"assignedTo",
			],
			boardGroupBy: "currentStageId",
		},
		{
			slot: "company",
			order: 3,
			defaultView: "board",
			cardFields: ["name", "headcount", "open_roles_count"],
			listColumns: [
				"name",
				"companyCode",
				"headcount",
				"open_roles_count",
				"fee_structure",
				"assignedTo",
			],
			boardGroupBy: "assignedTo",
		},
	],

	noteCategories: [
		{ name: "Urgent", bgColor: "#fecaca", isDefault: false, position: 0 },
		{ name: "Today", bgColor: "#fde68a", isDefault: true, position: 1 },
		{ name: "Interview Prep", bgColor: "#bae6fd", isDefault: false, position: 2 },
		{ name: "Reference", bgColor: "#ddd6fe", isDefault: false, position: 3 },
		{ name: "Done", bgColor: "#a7f3d0", isDefault: false, position: 4 },
	],

	tags: [
		{ name: "Passive candidate", color: "#6366f1" },
		{ name: "Active job seeker", color: "#22c55e" },
		{ name: "Referral", color: "#3b82f6" },
		{ name: "Boomerang", color: "#a855f7" },
		{ name: "Diversity hire", color: "#ec4899" },
		{ name: "Senior talent", color: "#f59e0b" },
		{ name: "Relocation needed", color: "#06b6d4" },
		{ name: "Counter-offered", color: "#ef4444" },
		{ name: "Warm lead", color: "#10b981" },
	],

	briefingDefaults: {
		morningBriefingEnabled: true,
		morningBriefingTime: "08:30",
	},

	taskDefaults: {
		defaultDueOffsetDays: 2,
		defaultPriority: "high",
		notifyAssignee: true,
		requireDealCode: false,
		reminderBeforeHours: 1,
	},

	fileUpload: {
		allowedMimeCategories: ["pdf", "document", "image"],
		maxSizeMb: 15,
	},

	aiPersona:
		"You are a recruiting operations assistant. Help the user source candidates, track them through the interview pipeline (Sourced → Screened → Phone → Onsite → Offer → Hired/Rejected/Withdrawn), and manage client relationships. Refer to leads as 'candidates', contacts as 'hiring managers', deals as 'placements', companies as 'client companies'. Understand notice periods, salary negotiations, counter-offers, and placement fees. Sensitive fields (resume, salary, comp band) must never be included in summaries unless the user has admin permissions. When a candidate is stuck in a stage past its stale threshold, suggest a follow-up. Always confirm before rejecting a candidate or withdrawing a placement.",

	dashboardMetrics: [
		"ai.morningBriefing",
		"ai.pulseRibbon",
		"ai.quickComposer",
		"leads.open",
		"deals.open",
		"deals.won",
		"tasks.dueToday",
		"tasks.list",
		"today.focus",
		"messages.recent",
		"activity.recent",
		"pipeline.salesPanel",
	],

	customRoles: [
		{
			name: "Recruiter",
			description: "Sources and screens candidates through the pipeline.",
			color: "#6366f1",
			permissions: [
				"leads.view",
				"leads.create",
				"leads.update",
				"leads.qualify",
				"leads.convert",
				"contacts.view",
				"contacts.create",
				"contacts.update",
				"companies.view",
				"deals.view",
				"deals.create",
				"deals.update",
				"deals.changeStage",
				"deals.viewValues",
				"deals.close",
				"notes.view",
				"notes.create",
				"notes.updateOwn",
				"notes.deleteOwn",
				"messages.view",
				"messages.send",
				"messages.editOwn",
				"messages.deleteOwn",
				"messages.subscribe",
				"tasks.view",
				"tasks.create",
				"tasks.manage",
				"tags.view",
				"tags.attach",
				"savedViews.view",
				"savedViews.createPersonal",
				"pipelines.view",
				"fieldDefinitions.view",
				"ai.use",
				"ai.viewHistory",
				"activityLogs.viewOwn",
				"notifications.viewOwn",
				"notifications.markRead",
				"files.view",
				"files.upload",
				"files.delete",
			],
		},
		{
			name: "Sourcer",
			description: "Top-of-funnel — finds and qualifies candidates.",
			color: "#a855f7",
			permissions: [
				"leads.view",
				"leads.create",
				"leads.update",
				"leads.qualify",
				"contacts.view",
				"companies.view",
				"deals.view",
				"deals.viewValues",
				"notes.view",
				"notes.create",
				"notes.updateOwn",
				"messages.view",
				"messages.send",
				"messages.editOwn",
				"messages.subscribe",
				"tasks.view",
				"tasks.create",
				"tasks.manage",
				"tags.view",
				"tags.attach",
				"savedViews.view",
				"savedViews.createPersonal",
				"pipelines.view",
				"fieldDefinitions.view",
				"ai.use",
				"activityLogs.viewOwn",
				"notifications.viewOwn",
				"notifications.markRead",
				"files.view",
				"files.upload",
				"files.delete",
			],
		},
	],

	savedViews: [
		{
			entityType: "lead",
			name: "Active candidates (mine)",
			scope: "user",
			isPinned: true,
			filters: JSON.stringify({ assignedToMe: true, statusNot: "converted" }),
			sortBy: "updatedAt",
			sortOrder: "desc",
		},
		{
			entityType: "lead",
			name: "Candidates needing follow-up",
			scope: "org",
			isPinned: true,
			filters: JSON.stringify({ staleAfterDays: 5 }),
			sortBy: "updatedAt",
			sortOrder: "asc",
		},
		{
			entityType: "deal",
			name: "Offers pending response",
			scope: "org",
			isPinned: true,
			filters: JSON.stringify({ stage: "OFR" }),
			sortBy: "stageEnteredAt",
			sortOrder: "asc",
		},
		{
			entityType: "deal",
			name: "Placements this month",
			scope: "org",
			isPinned: true,
			filters: JSON.stringify({ stage: "HIRED", wonWithin: "30d" }),
			sortBy: "wonAt",
			sortOrder: "desc",
		},
		{
			entityType: "deal",
			name: "Pipeline by stage",
			scope: "org",
			isPinned: false,
			filters: JSON.stringify({ excludeFinal: true }),
			sortBy: "currentStageId",
			sortOrder: "asc",
		},
	],

	// ─── Mock data (Phase 3A — deletable sample records) ──────────────
	// Lives in ../mockData/recruiting.ts so this file stays focused on
	// the structural template (pipelines, fields, modules, etc.).
	mockData: recruitingMockData,
};
