/**
 * Shared test helpers for seeding org members with proper roleId.
 *
 * Since orgMembers.roleId is required, tests must create an orgRole first
 * and reference it. This helper centralizes that pattern.
 */

const ROLE_PERMISSIONS: Record<string, string[]> = {
	owner: [
		"org.viewSettings",
		"org.editName",
		"org.editLogo",
		"org.editSettings",
		"org.viewBilling",
		"org.delete",
		"members.view",
		"members.invite",
		"members.cancelInvitation",
		"members.remove",
		"members.changeRole",
		"members.leave",
		"leads.view",
		"leads.create",
		"leads.update",
		"leads.delete",
		"leads.assign",
		"leads.qualify",
		"leads.convert",
		"contacts.view",
		"contacts.create",
		"contacts.update",
		"contacts.delete",
		"contacts.assign",
		"companies.view",
		"companies.create",
		"companies.update",
		"companies.delete",
		"deals.view",
		"deals.create",
		"deals.update",
		"deals.delete",
		"deals.assign",
		"deals.changeStage",
		"deals.close",
		"notes.view",
		"notes.viewInternal",
		"notes.create",
		"notes.updateOwn",
		"notes.deleteOwn",
		"notes.deleteAny",
		"notes.pin",
		"reminders.view",
		"reminders.create",
		"reminders.manage",
		"tags.view",
		"tags.manage",
		"tags.attach",
		"savedViews.view",
		"savedViews.createPersonal",
		"savedViews.createOrg",
		"savedViews.delete",
		"pipelines.view",
		"pipelines.manage",
		"fieldDefinitions.view",
		"fieldDefinitions.manage",
		"activityLogs.viewOrg",
		"activityLogs.viewOwn",
		"notifications.viewOwn",
		"notifications.markRead",
		"ai.use",
		"ai.manageTools",
		"ai.viewHistory",
	],
	admin: [
		"org.viewSettings",
		"org.editSettings",
		"members.view",
		"members.invite",
		"members.cancelInvitation",
		"members.remove",
		"members.leave",
		"leads.view",
		"leads.create",
		"leads.update",
		"leads.delete",
		"leads.assign",
		"leads.qualify",
		"leads.convert",
		"contacts.view",
		"contacts.create",
		"contacts.update",
		"contacts.delete",
		"contacts.assign",
		"companies.view",
		"companies.create",
		"companies.update",
		"companies.delete",
		"deals.view",
		"deals.create",
		"deals.update",
		"deals.delete",
		"deals.assign",
		"deals.changeStage",
		"deals.close",
		"notes.view",
		"notes.viewInternal",
		"notes.create",
		"notes.updateOwn",
		"notes.deleteOwn",
		"notes.deleteAny",
		"notes.pin",
		"reminders.view",
		"reminders.create",
		"reminders.manage",
		"tags.view",
		"tags.manage",
		"tags.attach",
		"savedViews.view",
		"savedViews.createPersonal",
		"savedViews.createOrg",
		"savedViews.delete",
		"pipelines.view",
		"pipelines.manage",
		"fieldDefinitions.view",
		"fieldDefinitions.manage",
		"activityLogs.viewOrg",
		"activityLogs.viewOwn",
		"notifications.viewOwn",
		"notifications.markRead",
		"ai.use",
		"ai.manageTools",
		"ai.viewHistory",
	],
	member: [
		"members.view",
		"members.leave",
		"leads.view",
		"leads.create",
		"leads.update",
		"leads.qualify",
		"contacts.view",
		"contacts.create",
		"contacts.update",
		"companies.view",
		"companies.create",
		"companies.update",
		"deals.view",
		"deals.create",
		"deals.update",
		"deals.changeStage",
		"notes.view",
		"notes.create",
		"notes.updateOwn",
		"notes.deleteOwn",
		"reminders.view",
		"reminders.create",
		"reminders.manage",
		"tags.view",
		"tags.attach",
		"savedViews.view",
		"savedViews.createPersonal",
		"pipelines.view",
		"fieldDefinitions.view",
		"activityLogs.viewOwn",
		"notifications.viewOwn",
		"notifications.markRead",
		"ai.use",
		"ai.viewHistory",
	],
	viewer: [
		"members.view",
		"members.leave",
		"leads.view",
		"contacts.view",
		"companies.view",
		"deals.view",
		"notes.view",
		"reminders.view",
		"tags.view",
		"savedViews.view",
		"pipelines.view",
		"fieldDefinitions.view",
		"activityLogs.viewOwn",
		"notifications.viewOwn",
		"notifications.markRead",
		"ai.viewHistory",
	],
};

/**
 * Creates an orgRole and inserts an orgMember in one call.
 * Use in test setup where you need a member with a specific role.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function seedOrgMember(
	ctx: any,
	orgId: any,
	userId: any,
	roleName: "owner" | "admin" | "member" | "viewer",
) {
	const now = Date.now();
	const capitalize = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

	const roleId = await ctx.db.insert("orgRoles", {
		orgId,
		name: capitalize(roleName),
		permissions: ROLE_PERMISSIONS[roleName],
		isSystem: true,
		isDefault: roleName === "member",
		createdAt: now,
		updatedAt: now,
	});

	const memberId = await ctx.db.insert("orgMembers", {
		orgId,
		userId,
		roleId,
		joinedAt: now,
	});

	return { roleId, memberId };
}
