"use client";
/**
 * core/shell/shell/views/dashboard/cards/AIBriefingCard.tsx
 *
 * Dashboard widget showing the cached AI Morning Briefing.
 * Updated daily by cron; manual refresh button counts against quota.
 */
import { useMutation, useQuery } from "convex/react";
import { anyApi } from "convex/server";
import { Bot, RefreshCw, Sparkles } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import type { Id } from "@/convex/_generated/dataModel";
import { useOrgPermissions } from "@/core/shell/shared/hooks/useCurrentOrg";
import { toast } from "@/lib/toast";

interface Props {
	orgId: Id<"orgs">;
	orgSlug: string;
}

export function AIBriefingCard({ orgId }: Props) {
	const permissions = useOrgPermissions();
	const canRefresh = permissions.includes("ai.briefingRefresh");

	const briefing = useQuery(anyApi.ai.briefingsPublic.getLatest, { orgId }) as
		| {
				_id: string;
				summary: string;
				generatedAt: number;
				model: string;
				highlights?: Array<{ type: string; text: string }>;
		  }
		| null
		| undefined;

	const refresh = useMutation(anyApi.ai.briefingsPublic.refreshNow);
	const [refreshing, setRefreshing] = useState(false);

	async function handleRefresh() {
		setRefreshing(true);
		try {
			await refresh({ orgId });
			toast.success("Generating new briefing", "It will appear in a few seconds.");
		} catch (err) {
			toast.mutationError(err, "Could not refresh briefing.");
		} finally {
			setRefreshing(false);
		}
	}

	if (briefing === undefined) {
		// Loading
		return (
			<div className="flex h-32 items-center justify-center rounded-[var(--radius)] border bg-card">
				<Bot className="size-5 animate-pulse text-muted-foreground" />
			</div>
		);
	}

	if (briefing === null) {
		// No briefing yet
		return (
			<div className="flex flex-col gap-3 rounded-[var(--radius)] border bg-card p-4">
				<div className="flex items-center gap-2">
					<Sparkles className="size-4 text-primary" />
					<span className="font-semibold text-sm">AI Morning Briefing</span>
				</div>
				<p className="text-sm text-muted-foreground">
					Your daily briefing hasn't been generated yet. Click below to create one.
				</p>
				{canRefresh && (
					<Button
						size="sm"
						onClick={handleRefresh}
						disabled={refreshing}
						className="self-start gap-1.5"
					>
						<RefreshCw className={`size-3.5 ${refreshing ? "animate-spin" : ""}`} />
						Generate briefing
					</Button>
				)}
			</div>
		);
	}

	const generatedMinAgo = Math.floor((Date.now() - briefing.generatedAt) / 60000);
	const generatedLabel =
		generatedMinAgo < 1
			? "just now"
			: generatedMinAgo < 60
				? `${generatedMinAgo} min ago`
				: `${Math.floor(generatedMinAgo / 60)} h ago`;

	return (
		<div className="flex flex-col gap-3 rounded-[var(--radius)] border bg-card p-4">
			<div className="flex items-center gap-2">
				<Sparkles className="size-4 text-primary" />
				<span className="flex-1 font-semibold text-sm">AI Morning Briefing</span>
				<span className="text-[10px] text-muted-foreground/60">{generatedLabel}</span>
			</div>

			<div className="space-y-2 text-sm leading-relaxed text-foreground whitespace-pre-wrap">
				{briefing.summary}
			</div>

			{briefing.highlights && briefing.highlights.length > 0 && (
				<div className="flex flex-wrap gap-1.5 pt-1">
					{briefing.highlights.slice(0, 4).map((h) => (
						<span
							key={h.text}
							className="rounded-full bg-primary/10 px-2 py-0.5 text-[11px] font-medium text-primary"
						>
							{h.text}
						</span>
					))}
				</div>
			)}

			<div className="flex items-center justify-between gap-2 border-t border-border pt-2 text-[10px] text-muted-foreground">
				<span>Generated by {briefing.model}</span>
				{canRefresh && (
					<button
						type="button"
						onClick={handleRefresh}
						disabled={refreshing}
						className="flex items-center gap-1 hover:text-foreground transition-colors disabled:opacity-50"
					>
						<RefreshCw className={`size-3 ${refreshing ? "animate-spin" : ""}`} />
						Refresh
					</button>
				)}
			</div>
		</div>
	);
}
