"use client";
/**
 * core/shell/shell/views/dashboard/cards/DailyBriefingCard.tsx
 *
 * Sprint 5 — daily AI briefing card. Reads `aiBriefings` rows where
 * `scope = "daily-user"`. Renders the structured `payload`
 * (summary + highlights + actionItems) when present; falls back to
 * the legacy `summary` + `highlights[].text` shape so older rows still
 * render correctly until the migration sweeps them.
 *
 * Layout (Claude/OpenAI-style condensed insight pane):
 *   ┌───────────────────────────────────────────────┐
 *   │ ✨ AI Morning Briefing            · 5 min ago │
 *   │                                               │
 *   │ Summary headline (1-2 sentences)              │
 *   │                                               │
 *   │ • Highlight 1                                 │
 *   │ • Highlight 2                                 │
 *   │ • Highlight 3                                 │
 *   │                                               │
 *   │ [Action 1]  [Action 2]                        │
 *   │ ─────────────────────────────                 │
 *   │ Generated by claude-haiku-3-5     ↻ Refresh   │
 *   └───────────────────────────────────────────────┘
 */

import { useMutation, useQuery } from "convex/react";
import { anyApi } from "convex/server";
import { RefreshCw, Sparkles } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import type { Id } from "@/convex/_generated/dataModel";
import { AIMark } from "@/core/ai/components/AIMark";
import { useOrgPermissions } from "@/core/shell/shared/hooks/useCurrentOrg";
import { toast } from "@/lib/toast";

interface Props {
	orgId: Id<"orgs">;
	orgSlug: string;
}

type BriefingShape = {
	_id: string;
	summary: string;
	generatedAt: number;
	model: string;
	highlights?: Array<{ type: string; text: string }>;
	payload?: {
		summary: string;
		highlights: string[];
		actionItems: Array<{ label: string; url?: string; toolCall?: string }>;
		trend?: "up" | "down" | "flat";
	};
};

export function DailyBriefingCard({ orgId }: Props) {
	const permissions = useOrgPermissions();
	const canRefresh = permissions.includes("ai.briefingRefresh");

	const briefing = useQuery(anyApi.ai.briefingsPublic.todayForUser, { orgId }) as
		| BriefingShape
		| null
		| undefined;

	const refresh = useMutation(anyApi.ai.briefingsPublic.refreshNow);
	const [refreshing, setRefreshing] = useState(false);

	async function handleRefresh() {
		setRefreshing(true);
		try {
			await refresh({ orgId });
			toast.success("Generating new briefing", "It will appear in a few seconds.");
		} catch (err) {
			toast.mutationError(err, "Could not refresh briefing.");
		} finally {
			setRefreshing(false);
		}
	}

	if (briefing === undefined) {
		return (
			<div className="flex h-full min-h-[180px] items-center justify-center rounded-[var(--radius)] border bg-card">
				<AIMark size="size-5" tone="muted" className="animate-pulse" aria-hidden="true" />
			</div>
		);
	}

	if (briefing === null) {
		return (
			<div className="flex h-full min-h-[180px] flex-col gap-3 rounded-[var(--radius)] border bg-card p-4">
				<div className="flex items-center gap-2">
					<Sparkles className="size-4 text-primary" />
					<span className="font-semibold text-sm">AI Morning Briefing</span>
					<span className="ms-auto text-[10px] text-muted-foreground/60">
						· just for you
					</span>
				</div>
				<p className="text-sm leading-relaxed text-foreground">
					Wake up to a personalised summary of yesterday's activity and today's
					priorities.
				</p>
				<ul className="flex flex-col gap-1 text-xs text-muted-foreground">
					<li className="flex gap-2 leading-relaxed">
						<span className="text-primary">•</span>
						<span>What changed across your leads, deals, and tasks overnight</span>
					</li>
					<li className="flex gap-2 leading-relaxed">
						<span className="text-primary">•</span>
						<span>Top 3 priorities ranked by deal value + recency</span>
					</li>
					<li className="flex gap-2 leading-relaxed">
						<span className="text-primary">•</span>
						<span>One-tap action chips to follow up immediately</span>
					</li>
				</ul>
				<div className="mt-auto flex items-center justify-between gap-2 border-t border-border pt-2 text-[10px] text-muted-foreground">
					<span>Auto-generated daily at your morning time</span>
					{canRefresh && (
						<button
							type="button"
							onClick={handleRefresh}
							disabled={refreshing}
							className="flex items-center gap-1 hover:text-foreground transition-colors disabled:opacity-50"
						>
							<RefreshCw className={`size-3 ${refreshing ? "animate-spin" : ""}`} />
							Generate now
						</button>
					)}
				</div>
			</div>
		);
	}

	// Error briefings — when no AI key is available the action writes a
	// row with `model: "error:no_key"` so the user sees the failure
	// cause instead of a silent void.
	const isErrorBriefing = briefing.model?.startsWith("error:") ?? false;
	if (isErrorBriefing) {
		return (
			<div className="flex h-full min-h-[180px] flex-col gap-3 rounded-[var(--radius)] border border-amber-300/60 bg-amber-50/60 p-4 dark:border-amber-700/40 dark:bg-amber-950/20">
				<div className="flex items-center gap-2">
					<Sparkles className="size-4 text-amber-700 dark:text-amber-300" />
					<span className="font-semibold text-sm text-amber-900 dark:text-amber-100">
						AI Morning Briefing
					</span>
				</div>
				<p className="text-sm leading-relaxed text-amber-900/90 dark:text-amber-100/90 whitespace-pre-wrap">
					{briefing.summary}
				</p>
				{canRefresh && (
					<Button
						size="sm"
						variant="outline"
						onClick={handleRefresh}
						disabled={refreshing}
						className="mt-auto self-start gap-1.5"
					>
						<RefreshCw className={`size-3.5 ${refreshing ? "animate-spin" : ""}`} />
						Try again
					</Button>
				)}
			</div>
		);
	}

	// Prefer the structured payload when available; fall back to legacy
	// summary+highlights so pre-Sprint-5 rows still render.
	const summary = briefing.payload?.summary ?? briefing.summary;
	const highlights =
		briefing.payload?.highlights ??
		(briefing.highlights ?? []).map((h) => h.text).filter(Boolean);
	const actionItems = briefing.payload?.actionItems ?? [];

	const generatedMinAgo = Math.floor((Date.now() - briefing.generatedAt) / 60000);
	const generatedLabel =
		generatedMinAgo < 1
			? "just now"
			: generatedMinAgo < 60
				? `${generatedMinAgo} min ago`
				: `${Math.floor(generatedMinAgo / 60)} h ago`;

	return (
		<div className="flex h-full min-h-[180px] flex-col gap-3 rounded-[var(--radius)] border bg-card p-4">
			<div className="flex items-center gap-2">
				<Sparkles className="size-4 text-primary" />
				<span className="flex-1 font-semibold text-sm">AI Morning Briefing</span>
				<span className="text-[10px] text-muted-foreground/60">{generatedLabel}</span>
			</div>

			<p className="text-sm leading-relaxed text-foreground whitespace-pre-wrap">{summary}</p>

			{highlights.length > 0 && (
				<ul className="flex flex-col gap-1 text-xs text-foreground/90">
					{highlights.slice(0, 5).map((h, i) => (
						// biome-ignore lint/suspicious/noArrayIndexKey: highlights are plain strings the model can legitimately repeat (e.g. "Follow-up call"), so a bare key={h} collides; the <li> is stateless presentational markup, render-only and capped at 5, so the index disambiguates safely
						<li key={`${i}-${h}`} className="flex gap-2 leading-relaxed">
							<span className="text-primary">•</span>
							<span>{h}</span>
						</li>
					))}
				</ul>
			)}

			{actionItems.length > 0 && (
				<div className="flex flex-wrap gap-1.5 pt-1">
					{actionItems.slice(0, 3).map((a) =>
						a.url ? (
							<Button
								key={a.label}
								asChild
								size="sm"
								variant="outline"
								className="h-7 text-xs"
							>
								<Link href={a.url}>{a.label}</Link>
							</Button>
						) : (
							<span
								key={a.label}
								className="rounded-full bg-primary/10 px-2 py-0.5 text-[11px] font-medium text-primary"
							>
								{a.label}
							</span>
						),
					)}
				</div>
			)}

			<div className="mt-auto flex items-center justify-between gap-2 border-t border-border pt-2 text-[10px] text-muted-foreground">
				<span>Generated by {briefing.model}</span>
				{canRefresh && (
					<button
						type="button"
						onClick={handleRefresh}
						disabled={refreshing}
						className="flex items-center gap-1 hover:text-foreground transition-colors disabled:opacity-50"
					>
						<RefreshCw className={`size-3 ${refreshing ? "animate-spin" : ""}`} />
						Refresh
					</button>
				)}
			</div>
		</div>
	);
}
