"use client";
/**
 * core/shell/shell/views/dashboard/cards/WeeklyInsightCard.tsx
 *
 * Sprint 5 — org-wide weekly insight card. Reads `aiBriefings` rows
 * where `scope = "weekly-org"`. Visible to every org member; cached
 * for 7 days. Generated by Sunday 23:00 UTC cron.
 *
 * Visual distinction from the daily card:
 *   - Different icon (TrendingUp instead of Sparkles)
 *   - Trend pill in the header (▲ up / ▬ flat / ▼ down)
 *   - "Org-wide" label so users understand this isn't just theirs
 *
 * Stage 1 of DASHBOARD-V2-PLAN.md (2026-05-28) — Generate now button
 * gated on `ai.briefingRefresh` (Owner / Admin by default), wired to
 * `briefingsPublic.refreshWeeklyNow` (rate-limited 1/day/org via
 * `enforceRateLimit`). Loading + empty-state heights match
 * DailyBriefingCard so the parent grid's `auto-rows-fr` keeps both
 * cards visually parallel.
 */

import { useMutation, useQuery } from "convex/react";
import { anyApi } from "convex/server";
import { Minus, RefreshCw, TrendingDown, TrendingUp } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import type { Id } from "@/convex/_generated/dataModel";
import { AIMark } from "@/core/ai/components/AIMark";
import { useOrgPermissions } from "@/core/shell/shared/hooks/useCurrentOrg";
import { toast } from "@/lib/toast";

interface Props {
	orgId: Id<"orgs">;
}

type WeeklyShape = {
	_id: string;
	summary: string;
	generatedAt: number;
	model: string;
	payload?: {
		summary: string;
		highlights: string[];
		actionItems: Array<{ label: string; url?: string; toolCall?: string }>;
		trend?: "up" | "down" | "flat";
	};
};

export function WeeklyInsightCard({ orgId }: Props) {
	const permissions = useOrgPermissions();
	const canRefresh = permissions.includes("ai.briefingRefresh");

	const insight = useQuery(anyApi.ai.briefingsPublic.thisWeekForOrg, { orgId }) as
		| WeeklyShape
		| null
		| undefined;

	const refresh = useMutation(anyApi.ai.briefingsPublic.refreshWeeklyNow);
	const [refreshing, setRefreshing] = useState(false);

	async function handleRefresh() {
		setRefreshing(true);
		try {
			await refresh({ orgId });
			toast.success(
				"Generating weekly insight",
				"It will appear in a few seconds — visible to every member.",
			);
		} catch (err) {
			toast.mutationError(err, "Could not generate weekly insight.");
		} finally {
			setRefreshing(false);
		}
	}

	if (insight === undefined) {
		return (
			<div className="flex h-full min-h-[180px] items-center justify-center rounded-[var(--radius)] border bg-card">
				<AIMark size="size-5" tone="muted" className="animate-pulse" aria-hidden="true" />
			</div>
		);
	}

	if (insight === null) {
		// Empty state mirrors the populated-state footer pattern (left:
		// "Generated by …", right: small action button) so both states
		// look visually identical inside the parent grid's
		// `auto-rows-fr` cell. The right-hand button label flips
		// `Generate` ↔ `Regenerate` based on whether content exists, so
		// users see the same affordance in the same place across states.
		//
		// Stage 7 (2026-05-29) — body upgraded from a one-liner to a
		// short value-prop paragraph + 3 bullets so an empty workspace
		// can still see what the weekly insight WILL surface once data
		// exists. Matches the daily briefing's empty state.
		return (
			<div className="flex h-full min-h-[180px] flex-col gap-3 rounded-[var(--radius)] border bg-card p-4">
				<div className="flex items-center gap-2">
					<TrendingUp className="size-4 text-muted-foreground" />
					<span className="font-semibold text-sm">Weekly insight</span>
					<span className="text-[10px] text-muted-foreground/60">· org-wide</span>
				</div>
				<p className="text-sm leading-relaxed text-foreground">
					A concise, org-wide pulse of the trailing 7 days — every Sunday night.
				</p>
				<ul className="flex flex-col gap-1 text-xs text-muted-foreground">
					<li className="flex gap-2 leading-relaxed">
						<span className="text-primary">•</span>
						<span>Pipeline movement — won, lost, advanced, stalled</span>
					</li>
					<li className="flex gap-2 leading-relaxed">
						<span className="text-primary">•</span>
						<span>Trend up / down / flat versus the previous week</span>
					</li>
					<li className="flex gap-2 leading-relaxed">
						<span className="text-primary">•</span>
						<span>Recommended actions to keep momentum</span>
					</li>
				</ul>
				<div className="mt-auto flex items-center justify-between gap-2 border-t border-border pt-2 text-[10px] text-muted-foreground">
					<span>Not yet generated</span>
					{canRefresh && (
						<button
							type="button"
							onClick={handleRefresh}
							disabled={refreshing}
							className="flex items-center gap-1 hover:text-foreground transition-colors disabled:opacity-50"
						>
							<RefreshCw className={`size-3 ${refreshing ? "animate-spin" : ""}`} />
							Generate
						</button>
					)}
				</div>
			</div>
		);
	}

	const summary = insight.payload?.summary ?? insight.summary;
	const highlights = insight.payload?.highlights ?? [];
	const actionItems = insight.payload?.actionItems ?? [];
	const trend = insight.payload?.trend ?? "flat";

	const TrendIcon = trend === "up" ? TrendingUp : trend === "down" ? TrendingDown : Minus;
	const trendTone =
		trend === "up"
			? "text-emerald-600"
			: trend === "down"
				? "text-rose-600"
				: "text-muted-foreground";

	const generatedDaysAgo = Math.floor((Date.now() - insight.generatedAt) / (24 * 60 * 60 * 1000));
	const label =
		generatedDaysAgo < 1
			? "today"
			: generatedDaysAgo === 1
				? "yesterday"
				: `${generatedDaysAgo}d ago`;

	return (
		<div className="flex h-full min-h-[180px] flex-col gap-3 rounded-[var(--radius)] border bg-card p-4">
			<div className="flex items-center gap-2">
				<TrendIcon className={`size-4 ${trendTone}`} />
				<span className="font-semibold text-sm">Weekly insight</span>
				<span className="text-[10px] text-muted-foreground/60">· org-wide</span>
				<span className="ms-auto text-[10px] text-muted-foreground/60">{label}</span>
			</div>

			<p className="text-sm leading-relaxed text-foreground whitespace-pre-wrap">{summary}</p>

			{highlights.length > 0 && (
				<ul className="flex flex-col gap-1 text-xs text-foreground/90">
					{highlights.slice(0, 5).map((h) => (
						<li key={h} className="flex gap-2 leading-relaxed">
							<span className="text-primary">•</span>
							<span>{h}</span>
						</li>
					))}
				</ul>
			)}

			{actionItems.length > 0 && (
				<div className="flex flex-wrap gap-1.5 pt-1">
					{actionItems.slice(0, 3).map((a) =>
						a.url ? (
							<Button
								key={a.label}
								asChild
								size="sm"
								variant="outline"
								className="h-7 text-xs"
							>
								<Link href={a.url}>{a.label}</Link>
							</Button>
						) : (
							<span
								key={a.label}
								className="rounded-full bg-primary/10 px-2 py-0.5 text-[11px] font-medium text-primary"
							>
								{a.label}
							</span>
						),
					)}
				</div>
			)}

			<div className="mt-auto flex items-center justify-between gap-2 border-t border-border pt-2 text-[10px] text-muted-foreground">
				<span>Generated by {insight.model}</span>
				{canRefresh && (
					<button
						type="button"
						onClick={handleRefresh}
						disabled={refreshing}
						className="flex items-center gap-1 hover:text-foreground transition-colors disabled:opacity-50"
					>
						<RefreshCw className={`size-3 ${refreshing ? "animate-spin" : ""}`} />
						Regenerate
					</button>
				)}
			</div>
		</div>
	);
}
