"use client";
/**
 * core/shell/shell/views/dashboard/cards/WeeklyInsightCard.tsx
 *
 * Sprint 5 — org-wide weekly insight card. Reads `aiBriefings` rows
 * where `scope = "weekly-org"`. Visible to every org member; cached
 * for 7 days. Generated by Sunday 23:00 UTC cron.
 *
 * Visual distinction from the daily card:
 *   - Different icon (TrendingUp instead of Sparkles)
 *   - Trend pill in the header (▲ up / ▬ flat / ▼ down)
 *   - "Org-wide" label so users understand this isn't just theirs
 *   - No refresh button (manual refresh would be expensive at org-scale;
 *     come back at Phase 4 if needed)
 */

import { useQuery } from "convex/react";
import { anyApi } from "convex/server";
import { Bot, Minus, TrendingDown, TrendingUp } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import type { Id } from "@/convex/_generated/dataModel";

interface Props {
	orgId: Id<"orgs">;
}

type WeeklyShape = {
	_id: string;
	summary: string;
	generatedAt: number;
	model: string;
	payload?: {
		summary: string;
		highlights: string[];
		actionItems: Array<{ label: string; url?: string; toolCall?: string }>;
		trend?: "up" | "down" | "flat";
	};
};

export function WeeklyInsightCard({ orgId }: Props) {
	const insight = useQuery(anyApi.ai.briefingsPublic.thisWeekForOrg, { orgId }) as
		| WeeklyShape
		| null
		| undefined;

	if (insight === undefined) {
		return (
			<div className="flex h-32 items-center justify-center rounded-[var(--radius)] border bg-card">
				<Bot className="size-5 animate-pulse text-muted-foreground" />
			</div>
		);
	}

	if (insight === null) {
		return (
			<div className="flex flex-col gap-2 rounded-[var(--radius)] border border-dashed bg-muted/30 p-4">
				<div className="flex items-center gap-2">
					<TrendingUp className="size-4 text-muted-foreground" />
					<span className="font-semibold text-sm">Weekly insight</span>
				</div>
				<p className="text-xs text-muted-foreground">
					Your first weekly insight will be generated on Sunday night. It analyses the
					last 7 days of pipeline activity for the whole workspace.
				</p>
			</div>
		);
	}

	const summary = insight.payload?.summary ?? insight.summary;
	const highlights = insight.payload?.highlights ?? [];
	const actionItems = insight.payload?.actionItems ?? [];
	const trend = insight.payload?.trend ?? "flat";

	const TrendIcon = trend === "up" ? TrendingUp : trend === "down" ? TrendingDown : Minus;
	const trendTone =
		trend === "up"
			? "text-emerald-600"
			: trend === "down"
				? "text-rose-600"
				: "text-muted-foreground";

	const generatedDaysAgo = Math.floor((Date.now() - insight.generatedAt) / (24 * 60 * 60 * 1000));
	const label =
		generatedDaysAgo < 1
			? "today"
			: generatedDaysAgo === 1
				? "yesterday"
				: `${generatedDaysAgo}d ago`;

	return (
		<div className="flex flex-col gap-3 rounded-[var(--radius)] border bg-card p-4">
			<div className="flex items-center gap-2">
				<TrendIcon className={`size-4 ${trendTone}`} />
				<span className="font-semibold text-sm">Weekly insight</span>
				<span className="text-[10px] text-muted-foreground/60">· org-wide</span>
				<span className="ms-auto text-[10px] text-muted-foreground/60">{label}</span>
			</div>

			<p className="text-sm leading-relaxed text-foreground whitespace-pre-wrap">{summary}</p>

			{highlights.length > 0 && (
				<ul className="flex flex-col gap-1 text-xs text-foreground/90">
					{highlights.slice(0, 5).map((h) => (
						<li key={h} className="flex gap-2 leading-relaxed">
							<span className="text-primary">•</span>
							<span>{h}</span>
						</li>
					))}
				</ul>
			)}

			{actionItems.length > 0 && (
				<div className="flex flex-wrap gap-1.5 pt-1">
					{actionItems.slice(0, 3).map((a) =>
						a.url ? (
							<Button
								key={a.label}
								asChild
								size="sm"
								variant="outline"
								className="h-7 text-xs"
							>
								<Link href={a.url}>{a.label}</Link>
							</Button>
						) : (
							<span
								key={a.label}
								className="rounded-full bg-primary/10 px-2 py-0.5 text-[11px] font-medium text-primary"
							>
								{a.label}
							</span>
						),
					)}
				</div>
			)}

			<div className="flex items-center gap-2 border-t border-border pt-2 text-[10px] text-muted-foreground">
				<span>Generated by {insight.model}</span>
			</div>
		</div>
	);
}
